/**
 * Digital SAT practice - Form B, Reading and Writing, MODULE 2 (LOWER route).
 *
 * ALL 27 items and ALL 27 passages are ORIGINAL, written from scratch for this
 * app. Domain blocks in the fixed order, easiest-to-hardest inside each block.
 * Do not sort. ids 6101-6199. Weighted easy: E 15 / M 9 / H 3.
 */

import type { SatMcq } from "../types";
import { R, RP } from "./rwFactory";

export const FORM_B_RW_LOWER: SatMcq[] = [
  // ── Craft and Structure ────────────────────────────────────────────────
  R(6101, "craft", "E", 0,
    "The village bakery opens at four in the morning and sells out by nine. There is no sign, no menu and no telephone number; customers simply know. The bakery has never advertised, and its owners say it has never needed to, because word of mouth has always been ______.",
    "Which choice completes the text with the most logical and precise word or phrase?",
    ["sufficient", "expensive", "unreliable", "temporary"],
    "Words in Context",
    "The bakery sells out daily without advertising, so word of mouth does the whole job - it is sufficient. Nothing suggests it is costly, unreliable or short-lived."),

  R(6102, "craft", "E", 0,
    "Desert plants survive long droughts in different ways. Some store water in thick stems; others send roots many metres down to reach groundwater. A third group simply waits: their seeds can lie in the sand for years, ______ until a rare heavy rain arrives.",
    "Which choice completes the text with the most logical and precise word or phrase?",
    ["dormant", "flowering", "growing", "visible"],
    "Words in Context",
    "Seeds that lie in the sand for years and wait for rain are dormant. Flowering, growing and being visible all describe activity, which is the opposite of waiting."),

  RP(6103, "craft", "E", 0,
    "The first maps of the underground railway tried to show the true positions of the stations, and the result was almost unreadable: lines crossed at odd angles and the outer stops crowded into the corners. The designer's decision to abandon geography and space the stations evenly made the map far easier to ______.",
    "Which choice completes the text with the most logical and precise word or phrase?",
    ["read", "print", "sell", "shorten"],
    "Words in Context",
    "The passage contrasts an \"almost unreadable\" map with the redesign, so the improvement is in readability. Printing, selling and shortening are never at issue."),

  R(6104, "craft", "E", 0,
    "A candle flame is not one colour but three. The base, where oxygen is plentiful, burns blue; the middle burns orange as carbon particles heat up; the tip glows yellow-white where those particles burn away completely. What looks like a single flame is really a record of how much oxygen reaches each part of it.",
    "Which choice best states the main purpose of the text?",
    ["To explain how the colours in a candle flame reflect differences in available oxygen.",
     "To argue that candles produce more light than they do heat.",
     "To describe how candles were manufactured before the modern era.",
     "To compare candle flames with the flames produced by gas burners."],
    "Text Structure and Purpose",
    "The text describes three colours and closes by tying them all to oxygen supply. It makes no claim about light and heat, no history, and no comparison with gas."),

  R(6105, "craft", "E", 0,
    "Many people assume that bamboo scaffolding is a relic kept alive by tradition. In fact it is still chosen for tall buildings in several cities because it is light, quick to erect, and flexible enough to sway in a typhoon without snapping - properties that steel tubing does not share.",
    "Which choice best states the main purpose of the text?",
    ["To correct an assumption by giving practical reasons for a traditional method.",
     "To describe the process of harvesting and treating bamboo for construction.",
     "To argue that steel scaffolding should be banned in typhoon-prone cities.",
     "To trace the history of scaffolding from antiquity to the present day."],
    "Text Structure and Purpose",
    "The text names an assumption, rejects it with \"in fact,\" and then lists working advantages. It offers no harvesting process, no ban, and no history."),

  R(6106, "craft", "M", 0,
    "Early sound recordings were made directly onto wax, and the wax could not be edited. A wrong note meant beginning the entire piece again. Performers of the period therefore developed a reputation for accuracy that owed less to their skill than to the ______ of the medium they were working in.",
    "Which choice completes the text with the most logical and precise word or phrase?",
    ["unforgivingness", "popularity", "expense", "novelty"],
    "Words in Context",
    "A medium in which one wrong note ruins the whole take is unforgiving, and that is what forced the accuracy. Its cost, popularity and novelty would not have that effect."),

  R(6107, "craft", "M", 0,
    "Text 1: Ecologist Ravi Damle argues that rewilding should mean removing human management entirely and letting a landscape find its own equilibrium. Text 2: Ingrid Solheim replies that most European landscapes have been shaped by grazing for millennia, so withdrawing management does not restore an earlier state - it produces a new one, usually dominated by a few aggressive species.",
    "Based on the texts, Solheim's main objection to Damle's position is that",
    ["withdrawing management produces a novel landscape rather than an earlier one.",
     "rewilding projects are too expensive for most European countries to fund.",
     "grazing animals should be removed from European landscapes entirely.",
     "human management of landscapes has never had any measurable effect."],
    "Cross-Text Connections",
    "Solheim's point is that there is no pristine state to return to, so removing management creates something new. She raises no cost objection, argues against removing grazing, and insists management has had large effects."),

  R(6108, "craft", "H", 0,
    "Tomas Beriz begins his study of the 1873 panic not with banks or bonds but with the telegraph. Prices that had once taken a week to cross the Atlantic now crossed in minutes, and a rumour could be acted on in London before it had been checked in New York. The crisis, he suggests, was not caused by the new speed, but it could not have taken the shape it did without it.",
    "Which choice best describes the function of the final sentence in the text?",
    ["It distinguishes a contributing condition from a cause.",
     "It concedes that the telegraph was irrelevant to the crisis.",
     "It identifies the specific banks that failed during the panic.",
     "It restates the definition of a financial panic given earlier."],
    "Text Structure and Purpose",
    "The sentence carefully separates \"not caused by\" from \"could not have taken the shape it did without\" - a condition, not a cause. It neither dismisses the telegraph nor names banks."),

  // ── Information and Ideas ──────────────────────────────────────────────
  R(6109, "info", "E", 0,
    "Salt was once so valuable that it was traded across the Sahara by camel caravan, slab for slab against gold. Its value came not from scarcity alone but from what it did: before refrigeration, salting was the only reliable way to keep meat and fish edible through a season.",
    "Which choice best states the main idea of the text?",
    ["Salt was highly valued largely because it was the only reliable way to preserve food.",
     "Salt was more difficult to obtain in the Sahara than gold was.",
     "Camel caravans were the fastest form of trade in the medieval world.",
     "Refrigeration was invented in order to replace the salting of food."],
    "Central Ideas and Details",
    "The final sentence gives the reason for the value: preservation. The text does not rank salt against gold in scarcity, discuss caravan speed, or explain why refrigeration was invented."),

  R(6110, "info", "E", 0,
    "A city council replaced the bulbs in 4,000 street lamps with LEDs over two years and monitored the electricity bill for the lighting network. In the year before the replacement the network used 5.9 million kilowatt-hours. In the year after it was finished, the figure was 2.1 million.",
    "According to the text, what happened after the replacement?",
    ["The lighting network used substantially less electricity than before.",
     "The lighting network used slightly more electricity than before.",
     "Electricity use by the lighting network stayed about the same.",
     "The council was unable to measure the network's electricity use."],
    "Central Ideas and Details",
    "Use fell from 5.9 million to 2.1 million kilowatt-hours, a large decrease. The other choices contradict those figures."),

  RP(6111, "info", "E", 0,
    "Octopuses have no bones at all. An octopus can therefore squeeze through any opening wider than its beak, which is the only hard part of its body. Aquarium keepers have learned to seal gaps that look far too small to matter, because an animal the size of a football can pass through a hole the size of a coin.",
    "Which choice best states the main idea of the text?",
    ["Having no bones except a beak lets an octopus pass through remarkably small openings.",
     "Octopuses are among the most intelligent animals kept in aquariums.",
     "An octopus's beak is the strongest part of its body.",
     "Aquarium tanks are usually built with openings the size of a coin."],
    "Central Ideas and Details",
    "The text links bonelessness to the beak-sized limit and then illustrates it with the aquarium example. Intelligence, beak strength, and tank design are never discussed."),

  R(6112, "info", "E", 0,
    "The forest has not burned in ninety years, and the undergrowth is now dense with young fir. Fire scars on the oldest trunks show that fires once passed through every eight to twelve years, clearing that undergrowth without killing the mature trees. Ecologists conclude that ______",
    "Which choice most logically completes the text?",
    ["the current density of undergrowth is a departure from the forest's long-term pattern.",
     "fire has never played any role in shaping this particular forest.",
     "the mature trees are unusually vulnerable to fire compared with young fir.",
     "the forest will remain free of fire for at least another ninety years."],
    "Inferences",
    "Scars record frequent fires and thin undergrowth for centuries; ninety years without fire has produced something different. Nothing supports the other three."),

  R(6113, "info", "M", 0,
    "Soil scientist Nadia Krol proposed that leaving crop residue on a field over winter, rather than ploughing it in, would reduce the loss of topsoil to wind and rain during the wettest months.",
    "Which finding, if true, would most directly support Krol's proposal?",
    ["Fields left covered with residue lost 40% less topsoil over the winter than ploughed fields nearby.",
     "Residue left on the surface decomposed more slowly than residue ploughed into the soil.",
     "Farmers in the region have ploughed residue into their fields for several generations.",
     "Ploughing a field requires more fuel per hectare than leaving residue in place."],
    "Command of Evidence",
    "The proposal is specifically about soil loss, so the evidence must compare erosion between covered and ploughed fields. Decomposition rate, tradition and fuel use leave the erosion claim untested."),

  R(6114, "info", "M", 0,
    "A clinic recorded how long patients waited to be seen, before and after it introduced an online appointment system. Staff expected the new system to shorten waits most for routine appointments, where scheduling had been least efficient.",
    "Which choice best describes data from the table that support the staff's expectation?",
    ["Waits for routine appointments fell by 19 minutes, a larger drop than for either other category.",
     "Waits for urgent appointments fell by more minutes than waits for routine appointments.",
     "Waits for follow-up appointments were unchanged after the new system was introduced.",
     "Waits increased in every category after the online system was introduced."],
    "Command of Evidence",
    "Routine waits fell from 47 to 28 minutes, a 19-minute drop, against 6 for urgent and 11 for follow-up. Every category improved, so the last two choices are wrong.",
    "<table><thead><tr><th>Appointment type</th><th>Mean wait before (min)</th><th>Mean wait after (min)</th></tr></thead><tbody><tr><td>Routine</td><td>47</td><td>28</td></tr><tr><td>Follow-up</td><td>33</td><td>22</td></tr><tr><td>Urgent</td><td>14</td><td>8</td></tr></tbody></table>"),

  R(6115, "info", "H", 0,
    "A ledger kept by a village schoolmaster records the number of pupils present each day from 1868 to 1879. Attendance falls sharply every year in late summer and again in October, and rises through the winter. The village's main crops were harvested in August and its orchards picked in October. Historians reading the ledger conclude that ______",
    "Which choice most logically completes the text?",
    ["attendance was shaped less by the school calendar than by the demand for children's labour.",
     "the schoolmaster recorded attendance inaccurately during the summer months.",
     "the village's children preferred attending school during the winter months.",
     "the school was formally closed during the harvest and the orchard picking."],
    "Inferences",
    "The two annual dips line up exactly with harvest and picking, which points to children working. Inaccurate recording, preference and formal closure are all consistent with the dips but unsupported by anything in the text."),

  // ── Standard English Conventions ───────────────────────────────────────
  R(6116, "conv", "E", 0,
    "The lake freezes solid by the end of December most years, and the ice road across it opens soon afterwards. Trucks use the road all winter ______",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    ["; it closes again when the thaw begins.",
     ", it closes again when the thaw begins.",
     " it closes again when the thaw begins.",
     ": it closes again, when the thaw begins."],
    "Boundaries",
    "Two independent clauses require a semicolon or a period. A comma alone is a splice and no punctuation is a run-on."),

  R(6117, "conv", "E", 0,
    "The archive received the photographs in nine cardboard boxes, none of them labelled and several of them water-damaged along one edge. The condition of the negatives ______ far better than anyone had expected.",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    ["was", "were", "have been", "are"],
    "Form, Structure, and Sense",
    "The subject is the singular \"condition\"; \"of the negatives\" is a prepositional phrase. The singular past \"was\" agrees and matches the narrative."),

  R(6118, "conv", "E", 0,
    "The comet was first recorded by astronomers in 1811 and has been observed on every return since. By the time it next appears, more than two hundred years ______ since that first sighting.",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    ["will have passed", "had passed", "passes", "was passing"],
    "Form, Structure, and Sense",
    "The passing will be complete before a future event - the comet's next appearance - so the future perfect is required."),

  R(6119, "conv", "E", 0,
    "Two rival teams announced the discovery of the same particle within a fortnight of one another, working from data collected on different continents. Each team maintained that ______ measurement was the more precise of the two.",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    ["its", "it's", "their", "they're"],
    "Form, Structure, and Sense",
    "\"Each team\" is singular, so the singular possessive \"its\" is correct. \"It's\" and \"they're\" are contractions."),

  R(6120, "conv", "M", 0,
    "Very few instruments survive from the workshop, and those that do are scattered across three continents. The viol in the museum's collection ______ built in 1698, is the only one still in playable condition.",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    [", which was", ", which was,", " which was", "; which was"],
    "Boundaries",
    "The nonrestrictive clause needs a comma at both ends, and the closing comma is already printed before \"is.\""),

  R(6121, "conv", "M", 0,
    "The expedition's daily routine left almost no room for improvisation, which was the point. Each morning the team broke camp, checked the sledges, and ______ the day's route against two separate sets of coordinates.",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    ["verified", "verifying", "to verify", "verify"],
    "Form, Structure, and Sense",
    "The series is built from simple past verbs - broke, checked, and verified. Only the past tense keeps the three items parallel."),

  R(6122, "conv", "M", 0,
    "Coastal fog forms when warm moist air drifts over a cold current, and the timing is remarkably regular along this stretch of shore. ______ the fog rolls in within twenty minutes of the same hour each afternoon.",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    ["During the summer months,", "During the summer months",
     "During, the summer months", "During the summer, months"],
    "Boundaries",
    "An introductory prepositional phrase takes a comma at its end, before the subject \"the fog.\" The other choices omit that comma or break up the phrase itself."),

  // ── Expression of Ideas ────────────────────────────────────────────────
  R(6123, "expr", "E", 0,
    "Paper recycling saves a great deal of energy and keeps waste out of landfill, and most cities now collect it separately. ______, paper fibres shorten each time they are reprocessed, so no sheet can be recycled indefinitely.",
    "Which choice completes the text with the most logical transition?",
    ["However", "Therefore", "Similarly", "In short"],
    "Transitions",
    "The second sentence sets a limitation against the benefits in the first, so a contrast transition is needed."),

  R(6124, "expr", "E", 0,
    "Honey does not spoil. Its sugar concentration is so high that bacteria cannot survive in it, and its acidity is low enough to discourage anything that might. ______, sealed jars recovered from ancient tombs have been found still edible.",
    "Which choice completes the text with the most logical transition?",
    ["As a result", "In contrast", "Nevertheless", "Instead"],
    "Transitions",
    "The ancient jars are a consequence of the chemistry just described, so a cause-and-effect transition fits. The other three signal opposition or substitution."),

  R(6125, "expr", "M", 0,
    "While researching a presentation, a student took the following notes: • The Iron Bridge at Coalbrookdale opened in 1781. • It was the first bridge in the world built entirely of cast iron. • Its builders used joints copied from carpentry, such as mortise and tenon. • Cast iron behaves very differently from timber under load.",
    "The student wants to emphasize that the bridge's builders were working without an established method. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
    ["Having no precedent for building in cast iron, the bridge's builders borrowed carpentry joints such as mortise and tenon, even though iron behaves very differently from timber under load.",
     "The Iron Bridge at Coalbrookdale opened to traffic in 1781.",
     "The Iron Bridge was the first bridge in the world to be built entirely of cast iron.",
     "Cast iron behaves very differently from timber when it is placed under load."],
    "Rhetorical Synthesis",
    "Borrowing joints from an unrelated material, despite the mismatch, is what shows there was no established method. The other choices give the date, the claim to priority, or the material property alone."),

  R(6126, "expr", "M", 0,
    "Most maps of the ocean floor are not built from direct measurement. Ships with sonar have surveyed only a small fraction of the sea bed; the rest is estimated from satellite readings of the sea surface, which bulges very slightly over underwater mountains. ______, most of what we call a map of the ocean floor is an inference from the shape of the water above it.",
    "Which choice completes the text with the most logical transition?",
    ["In other words", "By contrast", "For example", "Even so"],
    "Transitions",
    "The final sentence restates the preceding explanation more compactly, which calls for a restatement transition."),

  R(6127, "expr", "H", 0,
    "While researching a presentation, a student took the following notes: • Venice has been sinking slowly for centuries. • Groundwater extraction in the twentieth century accelerated the subsidence. • Extraction was banned in the 1970s and the rate of sinking slowed. • The city is still sinking by one to two millimetres a year.",
    "The student wants to explain that a human cause was identified and addressed, without suggesting the problem is solved. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
    ["Banning groundwater extraction in the 1970s slowed the subsidence that extraction had accelerated, but Venice is still sinking by one to two millimetres a year.",
     "Venice has been sinking slowly for many centuries.",
     "Groundwater extraction during the twentieth century accelerated the sinking of Venice.",
     "Extraction of groundwater beneath Venice was banned during the 1970s."],
    "Rhetorical Synthesis",
    "The goal has two halves - a cause addressed and a problem not solved - and only the first choice supplies both. The others give the long history, the cause, or the ban in isolation."),
];
