/**
 * Digital SAT practice - Form B, Math.
 *
 * ALL items are ORIGINAL, written from scratch for this app against the
 * published College Board blueprint (lib/sat/spec.ts). No College Board
 * material, no excerpted or adapted published questions.
 *
 * Order is AUTHORED order and is load-bearing: every multiple-choice item
 * first, then the grid-ins, each run easiest-to-hardest, domains mixed - which
 * is how the real digital SAT math module is arranged. Do not sort this array.
 * Choice order is also authored and must never be shuffled.
 *
 * ids 6301-6599.
 */

import type { SatMcq, SatSectionForm, SatSpr } from "../types";
import { M, MP, S } from "./mathFactory";

// ── Module 1: the broad mix (E 8 / M 9 / H 5) ─────────────────────────────
const M1: (SatMcq | SatSpr)[] = [
  M(6301, "alg", "E", 2, "If $x - 4 = 13$, what is the value of $x$?", ["9", "13", "17", "52"],
    "Linear equations in one variable", "Add 4 to both sides: $x = 17$."),
  M(6302, "psda", "E", 2,
    "A map is drawn to a scale of 1 centimetre to 25 kilometres. Two towns are 6 centimetres apart on the map. What is the actual distance between them, in kilometres?",
    ["31", "125", "150", "175"], "Ratios, rates, proportional relationships, and units",
    "Each centimetre represents 25 kilometres, so $6 \\times 25 = 150$ kilometres."),
  M(6303, "alg", "E", 0, "The function $g$ is defined by $g(x) = 7 - 2x$. What is the value of $g(3)$?",
    ["1", "$-1$", "13", "4"], "Linear functions",
    "Substitute 3: $g(3) = 7 - 2(3) = 7 - 6 = 1$."),
  M(6304, "adv", "E", 0, "Which expression is equivalent to $(x - 4)^2$?",
    ["$x^2 - 8x + 16$", "$x^2 + 16$", "$x^2 - 16$", "$x^2 - 8x - 16$"], "Equivalent expressions",
    "$(x-4)^2 = x^2 - 4x - 4x + 16 = x^2 - 8x + 16$. Squaring a binomial always produces a middle term."),
  M(6305, "geo", "E", 1,
    "A triangle has a base of 12 centimetres and a height of 5 centimetres. What is its area, in square centimetres?",
    ["17", "30", "34", "60"], "Area and volume",
    "The area of a triangle is $\\tfrac{1}{2}bh = \\tfrac{1}{2}(12)(5) = 30$. Forgetting the one-half gives 60.",
    '<svg viewBox="0 0 220 150" stroke="currentColor" fill="none" stroke-width="2" role="img"><polygon points="30,120 190,120 120,30" /><line x1="120" y1="30" x2="120" y2="120" stroke-dasharray="4 3" stroke-width="1.4" /><polyline points="120,106 106,106 106,120" stroke-width="1.2" /><text x="110" y="140" fill="currentColor" stroke="none" font-size="13" text-anchor="middle">12</text><text x="130" y="80" fill="currentColor" stroke="none" font-size="13">5</text></svg>'),
  MP(6306, "adv", "E", 0, "The function $f$ is defined by $f(x) = x^3$. What is the value of $f(-2)$?",
    ["$-8$", "8", "$-6$", "6"], "Nonlinear functions",
    "$(-2)^3 = -2 \\times -2 \\times -2 = -8$. An odd power keeps the negative sign."),
  M(6307, "alg", "M", 2, "If $\\dfrac{x + 3}{2} = 8$, what is the value of $x$?", ["5", "10", "13", "19"],
    "Linear equations in one variable", "Multiply both sides by 2: $x + 3 = 16$, so $x = 13$."),
  MP(6308, "psda", "M", 1,
    "The ratio of cats to dogs at an animal shelter is 3 to 5. If the shelter houses 40 dogs, how many cats does it house?",
    ["15", "24", "30", "66"], "Ratios, rates, proportional relationships, and units",
    "Set up $\\dfrac{3}{5} = \\dfrac{c}{40}$, so $5c = 120$ and $c = 24$."),
  M(6309, "adv", "M", 1, "What is the product of the solutions to $x^2 - 5x + 6 = 0$?", ["5", "6", "$-6$", "1"],
    "Nonlinear equations in one variable",
    "Factoring gives $(x-2)(x-3) = 0$, so the solutions are 2 and 3 and their product is 6. (For $x^2 + bx + c$, the product of the roots is $c$.)"),
  M(6310, "alg", "M", 0, "What is the slope of the line that passes through $(0, 3)$ and $(4, 11)$?",
    ["2", "$\\dfrac{1}{2}$", "4", "8"], "Linear equations in two variables",
    "Slope is the change in $y$ over the change in $x$: $\\dfrac{11 - 3}{4 - 0} = \\dfrac{8}{4} = 2$."),
  M(6311, "geo", "M", 0, "A circle has a diameter of 14. What is its circumference?",
    ["$14\\pi$", "$7\\pi$", "$49\\pi$", "$28\\pi$"], "Circles",
    "Circumference is $\\pi d$, so $14\\pi$. Using $2\\pi r$ with $r = 7$ gives the same result."),
  M(6312, "adv", "M", 0, "If $\\sqrt{x + 7} = 5$, what is the value of $x$?", ["18", "25", "32", "$-2$"],
    "Nonlinear equations in one variable", "Square both sides: $x + 7 = 25$, so $x = 18$."),
  M(6313, "alg", "M", 1, "If $3(x - 2) = 2x + 5$, what is the value of $x$?", ["1", "11", "$-1$", "$-11$"],
    "Linear equations in one variable", "Distribute: $3x - 6 = 2x + 5$. Subtract $2x$ and add 6: $x = 11$."),
  M(6314, "adv", "H", 0,
    "The function $h$ is defined by $h(x) = x^2 + bx + 9$, where $b$ is a constant. If $h$ has exactly one real zero, what is a possible value of $b$?",
    ["6", "3", "9", "18"], "Nonlinear functions",
    "One real zero means the discriminant is zero: $b^2 - 4(1)(9) = 0$, so $b^2 = 36$ and $b = 6$ or $b = -6$."),
  M(6315, "alg", "H", 0,
    "A tank holds 500 litres of water and is drained at a constant rate of 12 litres per minute. Which equation gives the volume $V$, in litres, remaining after $t$ minutes?",
    ["$V = 500 - 12t$", "$V = 500 + 12t$", "$V = 12t - 500$", "$V = 12(500 - t)$"], "Linear functions",
    "The tank starts at 500 and loses 12 litres each minute, so the rate is negative: $V = 500 - 12t$."),
  M(6316, "psda", "H", 0,
    "A dataset of seven values has a median of 12. The largest value in the set is then increased by 20 and no other value changes. What happens to the median?",
    ["It remains 12.", "It increases by 20.", "It increases by about 3.", "It cannot be determined from the information given."],
    "One-variable data: distributions and measures of center and spread",
    "With seven values the median is the fourth when they are ordered. Raising the largest value does not change which value sits fourth, so the median stays 12. The mean would change, but the median does not."),
  M(6317, "adv", "H", 0, "If $2^{x + 1} = 32$, what is the value of $x$?", ["4", "5", "15", "16"],
    "Nonlinear equations in one variable",
    "Write 32 as a power of 2: $32 = 2^5$, so $x + 1 = 5$ and $x = 4$."),

  S(6318, "alg", "E", ["27"], "If $x + 15 = 42$, what is the value of $x$?",
    "Linear equations in one variable", "Subtract 15 from both sides: $x = 27$."),
  S(6319, "psda", "E", ["12"],
    "In a class of 30 students, 40% play a musical instrument. How many students in the class play an instrument?",
    "Percentages", "$0.40 \\times 30 = 12$ students."),
  S(6320, "alg", "M", ["5"], "If $8x - 3 = 5x + 12$, what is the value of $x$?",
    "Linear equations in one variable", "Subtract $5x$: $3x - 3 = 12$. Add 3 and divide by 3: $x = 5$."),
  S(6321, "geo", "M", ["12"],
    "A rectangle has an area of 84 square centimetres and a width of 7 centimetres. What is its length, in centimetres?",
    "Area and volume", "Area is length times width, so the length is $84 \\div 7 = 12$."),
  S(6322, "adv", "H", ["1/2", ".5"],
    "The function $f$ is defined by $f(x) = 4x^2 - 12x + 5$. What is the smaller of the two values of $x$ for which $f(x) = 0$?",
    "Nonlinear equations in one variable",
    "Factor: $4x^2 - 12x + 5 = (2x - 1)(2x - 5)$, so $x = \\dfrac{1}{2}$ or $x = \\dfrac{5}{2}$. The smaller is $\\dfrac{1}{2}$, entered as 1/2 or .5."),
];

// ── Module 2, LOWER route (E 12 / M 8 / H 2) ──────────────────────────────
const M2_LOWER: (SatMcq | SatSpr)[] = [
  M(6401, "alg", "E", 0, "If $x + 6 = 20$, what is the value of $x$?", ["14", "26", "6", "120"],
    "Linear equations in one variable", "Subtract 6 from both sides: $x = 14$."),
  M(6402, "alg", "E", 1, "If $4x = 36$, what is the value of $x$?", ["4", "9", "32", "144"],
    "Linear equations in one variable", "Divide both sides by 4: $x = 9$."),
  M(6403, "psda", "E", 1, "What is 10% of 250?", ["2.5", "25", "240", "2,500"], "Percentages",
    "Ten percent is one tenth: $250 \\div 10 = 25$."),
  M(6404, "adv", "E", 0, "Which expression is equivalent to $2(x + 5)$?",
    ["$2x + 10$", "$2x + 5$", "$x + 10$", "$2x + 7$"], "Equivalent expressions",
    "Distribute the 2 across both terms: $2 \\cdot x + 2 \\cdot 5 = 2x + 10$."),
  M(6405, "geo", "E", 1, "A square has sides of length 7. What is its perimeter?", ["14", "28", "49", "21"],
    "Area and volume", "A square has four equal sides, so the perimeter is $4 \\times 7 = 28$. The value 49 is the area."),
  M(6406, "alg", "E", 0, "The function $f$ is defined by $f(x) = x + 9$. What is the value of $f(6)$?",
    ["15", "54", "3", "96"], "Linear functions", "Substitute 6 for $x$: $f(6) = 6 + 9 = 15$."),
  M(6407, "adv", "E", 1, "What is the value of $5^2$?", ["10", "25", "7", "32"], "Equivalent expressions",
    "$5^2$ means $5 \\times 5 = 25$, not $5 \\times 2$."),
  MP(6408, "psda", "E", 0,
    "A bag contains 4 red marbles and 6 blue marbles. If one marble is drawn at random, what is the probability that it is red?",
    ["$\\dfrac{2}{5}$", "$\\dfrac{3}{5}$", "$\\dfrac{1}{4}$", "$\\dfrac{4}{6}$"],
    "Probability and conditional probability",
    "There are 10 marbles in total and 4 are red, so the probability is $\\dfrac{4}{10} = \\dfrac{2}{5}$."),
  M(6409, "adv", "E", 0, "Which expression is equivalent to $x^3 \\cdot x^4$?",
    ["$x^7$", "$x^{12}$", "$x$", "$2x^7$"], "Equivalent expressions",
    "Multiplying powers with the same base adds the exponents: $x^{3+4} = x^7$."),
  MP(6410, "alg", "E", 1, "If $y = 3x$ and $x = 4$, what is the value of $y$?", ["7", "12", "34", "0.75"],
    "Linear equations in two variables", "Substitute 4 for $x$: $y = 3(4) = 12$."),
  M(6411, "alg", "M", 0, "If $2x + 9 = 25$, what is the value of $x$?", ["8", "17", "16", "34"],
    "Linear equations in one variable", "Subtract 9: $2x = 16$. Divide by 2: $x = 8$."),
  M(6412, "adv", "M", 0, "What are the solutions to $x^2 - 16 = 0$?",
    ["$x = 4$ and $x = -4$", "$x = 4$ only", "$x = 16$ and $x = -16$", "$x = 8$"],
    "Nonlinear equations in one variable",
    "$x^2 = 16$ has two solutions, since both $4^2$ and $(-4)^2$ equal 16."),
  M(6413, "psda", "M", 1,
    "A train travels 240 kilometres in 4 hours. What is its average speed, in kilometres per hour?",
    ["40", "60", "80", "960"], "Ratios, rates, proportional relationships, and units",
    "Average speed is distance divided by time: $240 \\div 4 = 60$."),
  M(6414, "geo", "M", 0, "A right triangle has legs of length 9 and 12. What is the length of its hypotenuse?",
    ["15", "21", "$\\sqrt{63}$", "18"], "Right triangles and trigonometry",
    "By the Pythagorean theorem, $9^2 + 12^2 = 81 + 144 = 225$, and $\\sqrt{225} = 15$.",
    '<svg viewBox="0 0 210 150" stroke="currentColor" fill="none" stroke-width="2" role="img"><polygon points="35,120 180,120 35,25" /><polyline points="35,106 49,106 49,120" stroke-width="1.4" /><text x="105" y="140" fill="currentColor" stroke="none" font-size="13" text-anchor="middle">12</text><text x="18" y="75" fill="currentColor" stroke="none" font-size="13" text-anchor="middle">9</text><text x="130" y="60" fill="currentColor" stroke="none" font-size="13" text-anchor="middle">?</text></svg>'),
  M(6415, "alg", "M", 1, "If $5x - 4 = 3x + 10$, what is the value of $x$?", ["3", "7", "14", "$-7$"],
    "Linear equations in one variable", "Subtract $3x$: $2x - 4 = 10$. Add 4 and divide by 2: $x = 7$."),
  M(6416, "adv", "M", 1, "The function $f$ is defined by $f(x) = 2x^2$. What is the value of $f(3)$?",
    ["12", "18", "36", "6"], "Nonlinear functions",
    "Square first, then multiply: $f(3) = 2(3^2) = 2(9) = 18$. Doubling before squaring gives 36."),
  M(6417, "adv", "H", 0, "What is the solution to $x^2 + 6x + 9 = 0$?", ["$x = -3$", "$x = 3$", "$x = -9$", "$x = 9$"],
    "Nonlinear equations in one variable",
    "The left side is a perfect square: $(x + 3)^2 = 0$, so $x = -3$ is the only solution."),

  S(6418, "alg", "E", ["13"], "If $x - 9 = 4$, what is the value of $x$?",
    "Linear equations in one variable", "Add 9 to both sides: $x = 13$."),
  S(6419, "psda", "E", ["15"],
    "A shop sells 6 identical pens for a total of 90 baht. At this rate, what is the price of one pen, in baht?",
    "Ratios, rates, proportional relationships, and units", "$90 \\div 6 = 15$ baht per pen."),
  S(6420, "alg", "M", ["21"], "If $\\dfrac{x}{3} = 7$, what is the value of $x$?",
    "Linear equations in one variable", "Multiply both sides by 3: $x = 21$."),
  S(6421, "geo", "M", ["26"],
    "A rectangle has a length of 9 and a width of 4. What is its perimeter?",
    "Area and volume", "Perimeter is $2(\\text{length} + \\text{width}) = 2(9 + 4) = 26$. The value 36 is the area.",
    '<svg viewBox="0 0 210 130" stroke="currentColor" fill="none" stroke-width="2" role="img"><rect x="35" y="30" width="140" height="62" /><text x="105" y="112" fill="currentColor" stroke="none" font-size="13" text-anchor="middle">9</text><text x="20" y="66" fill="currentColor" stroke="none" font-size="13">4</text></svg>'),
  S(6422, "adv", "H", ["5"],
    "The function $f$ is defined by $f(x) = x^2 - 5x + 4$. What is the sum of the two values of $x$ for which $f(x) = 0$?",
    "Nonlinear equations in one variable",
    "Factor: $(x - 1)(x - 4) = 0$, so the solutions are 1 and 4 and their sum is 5."),
];

// ── Module 2, UPPER route (E 2 / M 8 / H 12) ──────────────────────────────
const M2_UPPER: (SatMcq | SatSpr)[] = [
  M(6501, "alg", "E", 1, "If $6x = 54$, what is the value of $x$?", ["6", "9", "48", "324"],
    "Linear equations in one variable", "Divide both sides by 6: $x = 9$."),
  M(6502, "adv", "E", 0, "Which expression is equivalent to $(3x)^2$?",
    ["$9x^2$", "$6x^2$", "$3x^2$", "$9x$"], "Equivalent expressions",
    "The exponent applies to the whole product: $(3x)^2 = 3^2 \\cdot x^2 = 9x^2$."),
  MP(6503, "alg", "M", 0,
    "In the $xy$-plane, the line $y = kx - 2$ passes through the point $(3, 7)$. What is the value of $k$?",
    ["3", "2", "5", "9"], "Linear equations in two variables",
    "Substitute the point: $7 = 3k - 2$, so $3k = 9$ and $k = 3$."),
  MP(6504, "psda", "M", 1,
    "The mean of four numbers is 21. Three of the numbers are 15, 22 and 26. What is the fourth number?",
    ["18", "21", "24", "27"], "One-variable data: distributions and measures of center and spread",
    "The four numbers total $4 \\times 21 = 84$. The three given numbers sum to 63, so the fourth is $84 - 63 = 21$."),
  M(6505, "adv", "M", 0, "What is the sum of the solutions to $x^2 - 9x + 20 = 0$?", ["9", "20", "$-9$", "5"],
    "Nonlinear equations in one variable",
    "Factoring gives $(x - 4)(x - 5) = 0$, so the solutions are 4 and 5 and their sum is 9."),
  M(6506, "geo", "M", 0, "A circle has an area of $25\\pi$. What is its radius?",
    ["5", "25", "$\\sqrt{5}$", "12.5"], "Circles",
    "From $A = \\pi r^2 = 25\\pi$, we get $r^2 = 25$ and so $r = 5$."),
  M(6507, "alg", "M", 0, "If $3x - 2y = 12$ and $y = 3$, what is the value of $x$?", ["6", "2", "18", "$-6$"],
    "Systems of two linear equations in two variables",
    "Substitute $y = 3$: $3x - 6 = 12$, so $3x = 18$ and $x = 6$."),
  M(6508, "adv", "M", 0, "If $5^{x} = 125$, what is the value of $x$?", ["3", "5", "25", "625"],
    "Nonlinear equations in one variable", "Write 125 as a power of 5: $125 = 5^3$, so $x = 3$."),
  M(6509, "alg", "H", 0,
    "In the $xy$-plane, the line $y = -2x + c$ passes through the point $(4, -3)$. What is the value of $c$?",
    ["5", "$-11$", "11", "$-5$"], "Linear equations in two variables",
    "Substitute the point: $-3 = -2(4) + c = -8 + c$, so $c = 5$."),
  M(6510, "adv", "H", 0,
    "Which expression is equivalent to $\\dfrac{x^2 - 4}{x^2 - 4x + 4}$, where $x \\neq 2$?",
    ["$\\dfrac{x + 2}{x - 2}$", "$\\dfrac{x - 2}{x + 2}$", "$\\dfrac{x + 4}{x - 4}$", "$\\dfrac{1}{x - 2}$"],
    "Equivalent expressions",
    "The numerator is a difference of squares, $(x-2)(x+2)$, and the denominator is a perfect square, $(x-2)^2$. Cancelling one $(x-2)$ leaves $\\dfrac{x+2}{x-2}$."),
  M(6511, "psda", "H", 0,
    "Researchers observed that adults who drink tea daily tend to have lower blood pressure than adults who do not. Participants were not assigned to groups; the researchers simply recorded existing habits. Which conclusion is best supported?",
    ["Daily tea drinking is associated with lower blood pressure, but a causal link cannot be established.",
     "Drinking tea daily causes blood pressure to fall.",
     "Having lower blood pressure causes people to drink more tea.",
     "There is no relationship between tea drinking and blood pressure."],
    "Evaluating statistical claims: observational studies and experiments",
    "Without random assignment this is an observational study, which can establish association but not causation. The data do show a relationship, so the last choice is wrong too."),
  M(6512, "alg", "H", 2,
    "A print shop charges a fixed setup fee plus a fixed price per copy. An order of 200 copies costs 1,700 baht, and an order of 500 copies costs 3,500 baht. What is the price per copy, in baht?",
    ["4", "5", "6", "8"], "Linear functions",
    "The extra 300 copies cost $3{,}500 - 1{,}700 = 1{,}800$ baht, so each copy costs $1{,}800 \\div 300 = 6$ baht. (The setup fee is then $1{,}700 - 200(6) = 500$ baht.)"),
  M(6513, "adv", "H", 0,
    "The function $f$ is defined by $f(x) = -(x + 2)^2 + 7$. What is the maximum value of $f(x)$?",
    ["7", "$-7$", "2", "$-2$"], "Nonlinear functions",
    "The term $-(x+2)^2$ is never positive and equals 0 when $x = -2$. So the largest value $f$ can take is $0 + 7 = 7$."),
  M(6514, "geo", "H", 0,
    "In a right triangle, an acute angle $\\theta$ satisfies $\\tan\\theta = \\dfrac{5}{12}$. What is the value of $\\sin\\theta$?",
    ["$\\dfrac{5}{13}$", "$\\dfrac{12}{13}$", "$\\dfrac{13}{5}$", "$\\dfrac{5}{12}$"],
    "Right triangles and trigonometry",
    "Tangent is opposite over adjacent, so the legs are 5 and 12 and the hypotenuse is $\\sqrt{25 + 144} = 13$. Sine is opposite over hypotenuse: $\\dfrac{5}{13}$.",
    '<svg viewBox="0 0 210 150" stroke="currentColor" fill="none" stroke-width="2" role="img"><polygon points="35,120 180,120 35,25" /><polyline points="35,106 49,106 49,120" stroke-width="1.4" /><text x="105" y="140" fill="currentColor" stroke="none" font-size="13" text-anchor="middle">12</text><text x="18" y="75" fill="currentColor" stroke="none" font-size="13" text-anchor="middle">5</text><text x="130" y="60" fill="currentColor" stroke="none" font-size="13" text-anchor="middle">?</text><text x="150" y="112" fill="currentColor" stroke="none" font-size="12">&#952;</text></svg>'),
  M(6515, "alg", "H", 0, "Which of the following describes all solutions to $|2x + 1| \\le 7$?",
    ["$-4 \\le x \\le 3$", "$x \\le -4$ or $x \\ge 3$", "$-3 \\le x \\le 4$", "$x \\le 3$"],
    "Linear inequalities in one or two variables",
    "An absolute value at most 7 means $-7 \\le 2x + 1 \\le 7$. Subtracting 1 gives $-8 \\le 2x \\le 6$, and dividing by 2 gives $-4 \\le x \\le 3$."),
  M(6516, "adv", "H", 0,
    "The functions $f$ and $g$ are defined by $f(x) = 3x - 4$ and $g(x) = x^2$. What is the value of $g(f(2))$?",
    ["4", "8", "2", "36"], "Nonlinear functions",
    "Work from the inside out: $f(2) = 3(2) - 4 = 2$, then $g(2) = 2^2 = 4$. Reversing the order would give $g(2)=4$ then $f(4)=8$."),
  M(6517, "psda", "H", 0,
    "A set of twenty test scores has a mean of 74 and a median of 78. Which statement is most likely true of the distribution of these scores?",
    ["A few unusually low scores pull the mean below the median.",
     "A few unusually high scores pull the mean above the median.",
     "The scores are distributed symmetrically about 76.",
     "All twenty of the scores are below 74."],
    "One-variable data: distributions and measures of center and spread",
    "The mean sits below the median, which happens when a small number of very low values drag the average down. The median resists such outliers, which is why it stays higher."),

  S(6518, "alg", "M", ["8"], "If $\\dfrac{5x}{2} = 20$, what is the value of $x$?",
    "Linear equations in one variable", "Multiply both sides by 2: $5x = 40$. Divide by 5: $x = 8$."),
  S(6519, "psda", "M", ["675"],
    "A jacket priced at 900 baht is discounted by 25%. What is the sale price, in baht?",
    "Percentages", "A 25% discount leaves 75% of the price: $0.75 \\times 900 = 675$ baht."),
  S(6520, "alg", "H", ["7/5", "1.4"], "If $9x + 2 = 4x + 9$, what is the value of $x$?",
    "Linear equations in one variable",
    "Subtract $4x$: $5x + 2 = 9$. Subtract 2: $5x = 7$, so $x = \\dfrac{7}{5}$. You may enter 7/5 or 1.4."),
  S(6521, "geo", "H", ["21"],
    "A cone has a radius of 3 and a height of 7. The volume of the cone is $k\\pi$. What is the value of $k$?",
    "Area and volume",
    "The volume of a cone is $\\tfrac{1}{3}\\pi r^2 h = \\tfrac{1}{3}\\pi(9)(7) = 21\\pi$, so $k = 21$.",
    '<svg viewBox="0 0 200 165" stroke="currentColor" fill="none" stroke-width="2" role="img"><ellipse cx="100" cy="130" rx="45" ry="15" /><line x1="55" y1="130" x2="100" y2="25" /><line x1="145" y1="130" x2="100" y2="25" /><line x1="100" y1="25" x2="100" y2="130" stroke-dasharray="4 3" stroke-width="1.4" /><line x1="100" y1="130" x2="145" y2="130" stroke-dasharray="4 3" stroke-width="1.4" /><text x="122" y="146" fill="currentColor" stroke="none" font-size="12">3</text><text x="106" y="80" fill="currentColor" stroke="none" font-size="12">7</text></svg>'),
  S(6522, "adv", "H", ["1/2", ".5"],
    "The function $f$ is defined by $f(x) = 2x^2 + 5x - 3$. What is the positive value of $x$ for which $f(x) = 0$?",
    "Nonlinear equations in one variable",
    "Factor: $2x^2 + 5x - 3 = (2x - 1)(x + 3)$, so $x = \\dfrac{1}{2}$ or $x = -3$. The positive value is $\\dfrac{1}{2}$."),
];

export const FORM_B_MATH: SatSectionForm = { m1: M1, lower: M2_LOWER, upper: M2_UPPER };
