/**
 * Digital SAT practice - Form A, Reading and Writing, MODULE 2 (UPPER route).
 *
 * Reached when module 1 went well. Same blueprint and same 27 items, weighted
 * toward the hard end: E 3 / M 9 / H 15. This is the only route that reaches
 * the top of the Reading and Writing scale.
 *
 * ALL items and ALL passages are ORIGINAL, written from scratch for this app.
 * Domain blocks in the fixed order, easiest-to-hardest inside each block.
 * Do not sort this array, and never shuffle the choices. ids 5201-5299.
 */

import type { SatMcq } from "../types";
import { R, RP } from "./rwFactory";

export const FORM_A_RW_UPPER: SatMcq[] = [
  // ── Craft and Structure ────────────────────────────────────────────────
  RP(5201, "craft", "E", 0,
    "A wind tunnel does not test whether an aircraft will fly. It tests a scale model in a controlled airflow, and engineers use the resulting measurements to predict how the full-size machine will behave. The tunnel's whole value lies in how faithfully those small-scale results ______ to the real aircraft.",
    "Which choice completes the text with the most logical and precise word or phrase?",
    ["transfer", "object", "belong", "respond"],
    "Words in Context",
    "The question is whether findings from the model carry over to the full-size aircraft, which is what \"transfer\" means. Results do not object, belong, or respond to an aircraft."),

  R(5202, "craft", "M", 0,
    "The composer left no instructions about tempo, and performers have filled the gap with wildly divergent choices. One conductor takes the second movement in eleven minutes; another stretches it past nineteen. Because the score is ______ on the matter, neither reading can properly be called incorrect.",
    "Which choice completes the text with the most logical and precise word or phrase?",
    ["silent", "emphatic", "precise", "mistaken"],
    "Words in Context",
    "The composer \"left no instructions,\" so the score says nothing - it is silent. \"Emphatic\" and \"precise\" would mean the opposite, and a score that gives no instruction cannot be mistaken about one."),

  R(5203, "craft", "M", 0,
    "Anthropologist Ines Obarrio spends the first third of her study establishing what her fieldwork cannot show. Her sample is small, her access was limited to a single season, and the community she worked with is unusual in ways she enumerates carefully. Only after this accounting does she turn to her findings.",
    "Which choice best describes the function of the first third of the study, as it is characterized in the text?",
    ["It delimits the scope of the claims that the findings can support.",
     "It summarizes the findings that the rest of the study will present.",
     "It criticizes the fieldwork methods used by other anthropologists.",
     "It explains why the author chose to study that particular community."],
    "Text Structure and Purpose",
    "Cataloguing what the fieldwork \"cannot show\" sets boundaries on the conclusions that follow. It is not a summary, not a critique of others, and not a justification of the site."),

  R(5204, "craft", "M", 0,
    "Text 1: Economist Hal Renner maintains that a universal basic income would reduce poverty most efficiently, because cash transfers avoid the administrative cost of testing eligibility. Text 2: Policy analyst Sofia Bram accepts that means-testing is expensive, but notes that a universal payment large enough to lift anyone out of poverty would also reach households that need nothing at all - and that the sum saved on administration is smaller than the sum spent on those households.",
    "Based on the texts, Bram would most likely argue that Renner's efficiency claim",
    ["overlooks the cost of paying households that are not poor.",
     "depends on an administrative expense that does not actually exist.",
     "applies only to countries with very large populations.",
     "is correct in principle but politically impossible to act on."],
    "Cross-Text Connections",
    "Bram grants the administrative saving and then weighs it against a cost Renner never counts. She does not deny that means-testing is expensive, raise population size, or call the plan politically impossible."),

  R(5205, "craft", "H", 0,
    "Reviewers of the first edition complained that the author's central argument was buried under qualifications. In the second edition the qualifications all remain, but each now appears in a footnote rather than in the body of the text. The argument itself, released from these interruptions, acquires a ______ it had previously lacked.",
    "Which choice completes the text with the most logical and precise word or phrase?",
    ["momentum", "modesty", "obscurity", "brevity"],
    "Words in Context",
    "Nothing was deleted - the qualifications merely moved - so the text is not shorter, which rules out \"brevity.\" What changes is that the argument now runs uninterrupted, gaining momentum. \"Modesty\" and \"obscurity\" are unrelated to the change described."),

  R(5206, "craft", "H", 0,
    "Scholars of the Peloponnesian War have generally read the speeches in Thucydides as reconstructions of what was actually said. Hesper's new study takes the opposite view, treating them as compositions through which the historian works out arguments he could not state in his own voice. The reading is not in itself new; what is new is the evidence Hesper marshals for it.",
    "Which choice best describes the function of the final sentence in the text?",
    ["It qualifies the claim of originality just made for Hesper's study.",
     "It concedes that Hesper's conclusion is probably mistaken.",
     "It restates the traditional interpretation described at the outset.",
     "It identifies the particular speeches Hesper analyses most closely."],
    "Text Structure and Purpose",
    "Having called the study \"new,\" the final sentence narrows what is actually new about it: the evidence, not the interpretation. It concedes nothing about correctness, restates no earlier view, and names no speeches."),

  R(5207, "craft", "H", 0,
    "Text 1: Palaeontologist Ruben Alcaz argues that the feathered forelimbs of certain small dinosaurs served for display, since the feathers are asymmetrically pigmented but structurally far too weak for flapping flight. Text 2: Lian Ostrove agrees the limbs could not have sustained flapping flight, but contends that feathers too weak for flapping are perfectly adequate for gliding, and that the asymmetric pigmentation Alcaz points to occurs in modern gliding birds as well.",
    "Based on the texts, Ostrove's response to Alcaz is best described as",
    ["accepting one of his premises while denying that it supports his conclusion.",
     "rejecting his premises and offering an entirely unrelated explanation.",
     "agreeing with his conclusion but questioning the evidence behind it.",
     "arguing that the fossil evidence is too fragmentary to interpret at all."],
    "Cross-Text Connections",
    "Ostrove explicitly grants the weak-feather premise, then shows it is compatible with gliding rather than display - so the premise does not carry Alcaz's conclusion. She does not reject the premises, accept the conclusion, or call the evidence uninterpretable."),

  R(5208, "craft", "H", 0,
    "A reader coming to Mavis Quill's late poems from her early ones notices first what has gone: the elaborate rhyme schemes, the classical allusions, the long syntactical suspensions. What has replaced them is harder to name. The lines are shorter and the vocabulary plainer, and yet the poems are not simpler - critics who have called them so have generally been answered by other critics.",
    "Which choice best describes the overall structure of the text?",
    ["It identifies an obvious change and then resists an easy reading of it.",
     "It traces a poet's development chronologically from youth to old age.",
     "It compares two poets who were writing in the same period.",
     "It defends the early poems against a common critical charge."],
    "Text Structure and Purpose",
    "The first half catalogues what is easy to see; the second half warns that the obvious inference - simpler - does not hold. There is no chronology, no second poet, and no defence of the early work."),

  // ── Information and Ideas ──────────────────────────────────────────────
  RP(5209, "info", "E", 0,
    "Antibiotic resistance spreads in two ways. Bacteria pass resistance genes to their own descendants, which is slow; they also exchange small rings of DNA called plasmids directly with unrelated bacteria, which is fast. The second route is why resistance can appear almost simultaneously in species that are only distantly related to one another.",
    "Which choice best states the main idea of the text?",
    ["Direct exchange of plasmids lets resistance spread quickly between unrelated bacteria.",
     "Resistance genes are always inherited from a bacterium's immediate ancestors.",
     "Distantly related bacteria are unable to acquire the same resistance genes.",
     "Plasmids are the only structures in a bacterium that carry genes at all."],
    "Central Ideas and Details",
    "The text names two routes and singles out plasmid exchange as the fast one that explains simultaneous appearance across species. The other choices contradict the passage."),

  R(5210, "info", "M", 0,
    "The manuscript's parchment was prepared from calfskin by a method used only in one narrow region, and its pigments include a blue mineral quarried some three thousand kilometres away. The scribe's hand, however, matches a workshop documented in a third location entirely. Historians conclude that ______",
    "Which choice most logically completes the text?",
    ["materials were traded over long distances to reach the workshop where the book was written.",
     "the scribe must in fact have worked in the region where the parchment was prepared.",
     "the blue pigment was manufactured locally rather than quarried at a distance.",
     "the manuscript is a later forgery assembled out of unrelated fragments."],
    "Inferences",
    "The scribe's hand fixes where the writing happened; the parchment and pigment came from two other places. The straightforward reading is that the materials travelled to the scribe. The other choices contradict the evidence given."),

  R(5211, "info", "M", 0,
    "Musicologist Tavi Renard argues that the folk melodies collected in one mountain valley in 1904 were not ancient local survivals, as the collector believed, but recent imports carried inland by seasonal labourers returning from the coast.",
    "Which finding, if true, would most directly support Renard's argument?",
    ["Nearly identical melodies were recorded on the coast a decade before the valley collection was made.",
     "The valley's residents in 1904 sang the melodies more often at harvest than at other times of year.",
     "The collector who recorded the valley melodies had himself worked on the coast as a young man.",
     "The melodies use a scale that is common in folk music throughout the country."],
    "Command of Evidence",
    "Renard's claim is about origin and direction of travel, so evidence must show the melodies existed on the coast first. Seasonal singing habits, the collector's biography, and a widespread scale do not establish where the tunes came from."),

  R(5212, "info", "H", 0,
    "A laboratory tested how storage temperature affects the germination rate of seeds after five years in storage. The team predicted that colder storage would preserve viability, but also that the benefit of further cooling would diminish below a certain point.",
    "Which choice best describes data from the table that support both parts of the team's prediction?",
    ["Germination rose sharply from 14% at 20 degrees to 87% at negative 5 degrees, but only to 91% at negative 18 degrees.",
     "Germination fell steadily as the storage temperature decreased from 20 degrees to negative 18 degrees.",
     "Germination was highest at 20 degrees and lowest at negative 18 degrees.",
     "Germination was identical at negative 5 degrees and at negative 18 degrees."],
    "Command of Evidence",
    "Both halves of the prediction must be covered: cooling helps (14% to 87%) and the extra benefit shrinks (87% to only 91%). The other choices reverse the trend or misstate the final two rows, which differ by four points.",
    "<table><thead><tr><th>Storage temperature (C)</th><th>Germination after 5 years (%)</th></tr></thead><tbody><tr><td>20</td><td>14</td></tr><tr><td>5</td><td>58</td></tr><tr><td>-5</td><td>87</td></tr><tr><td>-18</td><td>91</td></tr></tbody></table>"),

  R(5213, "info", "H", 0,
    "A city introduced a congestion charge in its central zone, and within a year traffic inside the zone fell by 18 percent. Traffic on the ring road just outside the zone rose by 4 percent over the same period, while total vehicle kilometres across the whole metropolitan area fell by 9 percent. An analyst reviewing these figures concluded that ______",
    "Which choice most logically completes the text?",
    ["some trips were diverted around the zone, but most of the reduction was genuine.",
     "all of the reduction inside the zone was offset by displacement onto the ring road.",
     "the charge had no measurable effect on driving anywhere in the city.",
     "drivers responded to the charge by making longer trips inside the charged zone."],
    "Inferences",
    "The 4 percent rise on the ring road shows some displacement, but the 9 percent fall across the whole area shows the drop was not merely relocation. Total kilometres falling rules out both \"no effect\" and \"fully offset.\""),

  R(5214, "info", "H", 0,
    "Attempts to date the earliest use of fire by hominins run into a problem of evidence. Ash and charcoal decay or wash away, and hearths leave traces only under unusual conditions of preservation. The oldest confirmed sites therefore mark not the beginning of fire use but the beginning of the surviving record of it - a distinction easy to state and surprisingly difficult to keep in view.",
    "Which choice best states the main idea of the text?",
    ["The oldest confirmed fire sites show when evidence began to survive, not when fire use began.",
     "Hominins almost certainly did not use fire before the oldest confirmed sites were occupied.",
     "Ash and charcoal are the most durable forms of archaeological evidence available.",
     "Dating hominin sites is easier than dating the artefacts recovered from within them."],
    "Central Ideas and Details",
    "The final sentence draws exactly this distinction between the record and the practice. The second choice is the error the text warns against, and the third and fourth contradict or ignore the passage."),

  R(5215, "info", "H", 0,
    "In her study of nineteenth-century domestic account books, historian Wren Ackley argues that household budgets were in practice managed by women, even in families where men earned all of the income the books record.",
    "Which finding from the account books would most effectively support Ackley's argument?",
    ["The entries are overwhelmingly in the wives' handwriting and record decisions to defer or reallocate particular purchases.",
     "The books set out the husbands' weekly wages in a separate column at the front of each volume.",
     "Most of the households represented in the sample employed at least one live-in servant.",
     "The books were bound in inexpensive materials and were generally stored in kitchens."],
    "Command of Evidence",
    "Ackley's claim is about who managed the budget, so the evidence must show women making allocation decisions - handwriting plus deferred and reallocated purchases does exactly that. Wage columns, servants, and bindings say nothing about who decided."),

  // ── Standard English Conventions ───────────────────────────────────────
  R(5216, "conv", "E", 0,
    "The observatory was built above the inversion layer, which is the main reason its images are so sharp. Below that layer the air is turbulent and thick with dust ______",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    ["; above it, the sky is remarkably steady.",
     ", above it, the sky is remarkably steady.",
     " above it, the sky is remarkably steady.",
     ": above it the sky is, remarkably steady."],
    "Boundaries",
    "Two independent clauses need a semicolon or a period. A comma alone creates a splice, no punctuation creates a run-on, and the last choice separates the subject from its verb."),

  R(5217, "conv", "M", 0,
    "The commission's report was unusual in declining to assign blame to any single party involved in the accident. It concluded that the failure lay neither in the original design ______ in the maintenance schedule, but in the absence of any procedure for passing information between the two teams.",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    ["nor", "or", "and", "not"],
    "Form, Structure, and Sense",
    "\"Neither\" pairs only with \"nor.\" The other options break the correlative construction."),

  R(5218, "conv", "M", 0,
    "The gallery's newest acquisition is a mosaic panel that occupies an entire wall of the east room. Among the fragments mounted on the wall beside it ______ two pieces of window glass recovered from the same excavation.",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    ["are", "is", "was", "has been"],
    "Form, Structure, and Sense",
    "The sentence is inverted: the subject is the plural \"two pieces,\" which follows the verb. A plural subject takes \"are.\""),

  R(5219, "conv", "H", 0,
    "Later accounts blamed the weather, the route and the leader's judgement in roughly equal measure, and the argument has never entirely settled. The expedition's failure had a single cause, however, and the diaries name it plainly ______",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    [": fuel, exhausted two weeks short of the depot.",
     "; fuel, exhausted two weeks short of the depot.",
     ", fuel exhausted two weeks short of the depot.",
     " fuel; exhausted two weeks short of the depot."],
    "Boundaries",
    "What follows the blank is a noun phrase, not an independent clause, so only a colon can introduce it. A semicolon requires a full clause on both sides, and the remaining choices punctuate the phrase incorrectly."),

  R(5220, "conv", "H", 0,
    "The commission spent four years gathering testimony from people who had been children at the time of the events it examined. Its final report, running to more than nine hundred pages and drawing on interviews conducted in six languages, ______ the most complete account of the period yet assembled.",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    ["remains", "remain", "have remained", "are"],
    "Form, Structure, and Sense",
    "The subject is the singular \"report\"; everything between the commas is a modifier. Only the singular \"remains\" agrees with it."),

  R(5221, "conv", "H", 0,
    "The instrument's most delicate component is a quartz fibre thinner than a human hair, suspended inside a sealed vacuum housing. That fibre ______ must be replaced after every deep-ocean deployment.",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    [" - fragile, irreplaceable in the field, and startlingly expensive - ",
     ", fragile, irreplaceable in the field, and startlingly expensive - ",
     " - fragile, irreplaceable in the field, and startlingly expensive, ",
     ", fragile, irreplaceable in the field and startlingly expensive "],
    "Boundaries",
    "The interrupting element already contains commas, so it must be set off with a matching pair of dashes. Mixing a comma with a dash, or using commas alone, leaves the boundaries ambiguous."),

  R(5222, "conv", "H", 0,
    "The orchestra had rehearsed the symphony only twice before the recording session, and the players disagreed openly about several passages. In the end the ensemble recorded the work in a single take, and ______ disagreements are audible only to listeners who know the score very well.",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    ["its", "it's", "their", "theirs"],
    "Form, Structure, and Sense",
    "The antecedent in this clause is \"the ensemble,\" a singular noun, so the singular possessive \"its\" is required. \"It's\" is a contraction and \"theirs\" cannot precede a noun."),

  // ── Expression of Ideas ────────────────────────────────────────────────
  R(5223, "expr", "M", 0,
    "Desalination can supply fresh water to cities that have almost none of their own. The process is energy-intensive, however, and the concentrated brine it leaves behind has to be disposed of with some care. ______, it remains the only realistic option for several coastal cities in arid regions.",
    "Which choice completes the text with the most logical transition?",
    ["For all that", "Because of this", "In particular", "By the same token"],
    "Transitions",
    "The final sentence asserts desalination's value despite the drawbacks just listed, so a concessive transition is needed. \"Because of this\" makes the drawbacks the reason, which reverses the logic."),

  R(5224, "expr", "M", 0,
    "While researching a presentation, a student took the following notes: • The Aral Sea was once the fourth-largest lake in the world. • Soviet irrigation projects diverted its two feeder rivers beginning in the 1960s. • By 2007 the lake had shrunk to about a tenth of its original volume. • A dam completed in 2005 has since restored part of the northern basin.",
    "The student wants to emphasize that the decline has been partly reversed. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
    ["Although the lake had shrunk to roughly a tenth of its original volume by 2007, a dam completed in 2005 has since restored part of the northern basin.",
     "The Aral Sea was once the fourth-largest lake in the world.",
     "Soviet irrigation projects diverted the lake's two feeder rivers beginning in the 1960s.",
     "By 2007 the Aral Sea had shrunk to about a tenth of its original volume."],
    "Rhetorical Synthesis",
    "Only the first choice sets the loss against the recovery, which is what \"partly reversed\" requires. The others report scale, cause, or loss alone."),

  R(5225, "expr", "H", 0,
    "Most models of language acquisition assume that children learn word meanings by hearing words paired with the objects they name. Children who are congenitally blind, however, acquire words for colour and for visual appearance at close to the usual rate. ______, they go on to use those words in ways that match sighted speakers' usage almost exactly.",
    "Which choice completes the text with the most logical transition?",
    ["What is more", "In other words", "By contrast", "As a result"],
    "Transitions",
    "The final sentence adds a second, stronger fact in the same direction as the one before it, so an additive intensifier fits. It is not a restatement, not a contrast with the preceding sentence, and not a consequence of it."),

  R(5226, "expr", "H", 0,
    "The trial found that the drug reduced symptoms in 62 percent of participants, against 41 percent for the placebo, and the effect appeared strongest in participants under forty. ______, the trial enrolled only 180 people in total, and its authors caution that the age finding in particular will need replication.",
    "Which choice completes the text with the most logical transition?",
    ["That said", "Accordingly", "Likewise", "For example"],
    "Transitions",
    "The second sentence tempers the encouraging result with a limitation, which calls for a concessive transition. \"Accordingly\" would make the small sample a consequence of the result, and the other two add or illustrate."),

  R(5227, "expr", "H", 0,
    "While researching a presentation, a student took the following notes: • Glass eels migrate thousands of kilometres from the Sargasso Sea to European rivers. • European eel numbers have fallen by more than 90 percent since 1980. • Barriers such as weirs block access to much of their former river habitat. • Eel passes installed on some weirs have restored access to several hundred kilometres of river.",
    "The student wants to explain how one specific obstacle to eel recovery is being addressed. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
    ["Because barriers such as weirs block access to much of the eels' former river habitat, eel passes installed on some of them have restored access to several hundred kilometres of river.",
     "European eel numbers have fallen by more than 90 percent since 1980.",
     "Glass eels migrate thousands of kilometres from the Sargasso Sea to reach European rivers.",
     "Eel passes have been installed on some weirs in European rivers."],
    "Rhetorical Synthesis",
    "The goal names both an obstacle and its remedy, so the answer must pair the weirs with the passes and the access they restore. The last choice mentions the remedy but not the obstacle it addresses."),
];
