/**
 * Digital SAT practice - Form B, Reading and Writing, MODULE 2 (UPPER route).
 *
 * ALL 27 items and ALL 27 passages are ORIGINAL, written from scratch for this
 * app. Domain blocks in the fixed order, easiest-to-hardest inside each block.
 * Do not sort. ids 6201-6299. Weighted hard: E 3 / M 9 / H 15.
 */

import type { SatMcq } from "../types";
import { R, RP } from "./rwFactory";

export const FORM_B_RW_UPPER: SatMcq[] = [
  // ── Craft and Structure ────────────────────────────────────────────────
  RP(6201, "craft", "E", 0,
    "A conductor's score is not the document the players read from. It stacks every instrumental part in a single column, so that one glance takes in what thirty musicians are doing at a given moment. The layout serves ______, not performance.",
    "Which choice completes the text with the most logical and precise word or phrase?",
    ["comprehension", "decoration", "storage", "improvisation"],
    "Words in Context",
    "The stacked layout exists so the conductor can grasp all thirty parts at once, which is comprehension. The sentence explicitly excludes performance, and decoration and storage are never suggested."),

  R(6202, "craft", "M", 0,
    "The novel's narrator is a minor clerk who insists, again and again, that he understood nothing of the events he is describing. Readers who take him at his word find the book thin. Readers who do not find that almost every claim he makes is quietly ______ by the detail he supplies alongside it.",
    "Which choice completes the text with the most logical and precise word or phrase?",
    ["contradicted", "confirmed", "repeated", "translated"],
    "Words in Context",
    "The second group of readers doubts his claim of ignorance, and what licenses that doubt is detail working against the claim - contradicting it. \"Confirmed\" would give the first group's reading."),

  R(6203, "craft", "M", 0,
    "Economic historian Piet Vanheel devotes his opening chapter to explaining why the standard price index for the period cannot be trusted. The basket of goods it tracks was fixed in 1780 and never revised, so it went on weighting commodities that had largely vanished from ordinary households by 1850. Only after establishing this does he offer a series of his own.",
    "Which choice best describes the function of the opening chapter, as it is characterized in the text?",
    ["It justifies the author's decision to construct a new measure.",
     "It summarizes the conclusions the book will reach about prices.",
     "It surveys the range of sources available for the period.",
     "It concedes that the author's own series is equally unreliable."],
    "Text Structure and Purpose",
    "Showing that the existing index is unusable is what makes a replacement necessary, and the chapter's placement before his own series confirms the purpose. He does not summarize conclusions, survey sources, or undercut his own work."),

  R(6204, "craft", "M", 0,
    "Text 1: Neuroscientist Aya Fenn argues that the brain's capacity for change is greatest in childhood and declines steeply afterwards, which is why languages learned late are so rarely spoken without an accent. Text 2: Bruno Halstead accepts the evidence about accent but notes that adults typically learn a language in classrooms and spare hours while children are immersed in it all day - so the comparison holds age constant and almost nothing else.",
    "Based on the texts, Halstead's response to Fenn is best described as",
    ["arguing that her evidence cannot separate age from the circumstances of learning.",
     "denying that adult learners ever retain a foreign accent at all.",
     "claiming that children in fact learn languages more slowly than adults do.",
     "proposing that accent is unrelated to how a language is learned."],
    "Cross-Text Connections",
    "Halstead grants the accent data and objects that two variables move together, so the data cannot isolate age. He denies neither the accents nor the role of learning conditions."),

  R(6205, "craft", "H", 0,
    "For a decade the field treated the result as settled. Two later laboratories reported the same effect, and the original paper accumulated citations at a rate that made further checking seem redundant. It emerged only afterwards that both replications had drawn on the same flawed reagent, so what had looked like independent confirmation was in fact a single result ______ three times.",
    "Which choice completes the text with the most logical and precise word or phrase?",
    ["restated", "refuted", "predicted", "abandoned"],
    "Words in Context",
    "If all three findings trace to one flawed reagent, the later two added nothing new - the same result was simply restated. It was not refuted, predicted or abandoned during that decade."),

  R(6206, "craft", "H", 0,
    "Mira Kadlec's essay on urban trees is organized around a number she never defends: the claim that a mature street tree returns several times its planting cost in avoided drainage and cooling. She reports the figure, notes the wide range of estimates behind it, and then sets it aside entirely. Her argument, she says, would be unchanged if the number turned out to be half as large.",
    "Which choice best describes the function of the final sentence in the text?",
    ["It indicates that the essay's case does not rest on the contested figure.",
     "It concedes that the figure the essay reports is probably mistaken.",
     "It explains how the figure was calculated by earlier researchers.",
     "It identifies drainage as the more important of the two benefits."],
    "Text Structure and Purpose",
    "Saying the argument survives a halved figure detaches the case from the number - which is why she can set it aside. She does not call it wrong, explain its derivation, or rank the benefits."),

  R(6207, "craft", "H", 0,
    "Text 1: Archaeologist Iris Bergen argues that the settlement was abandoned suddenly, pointing to grain left in the storage pits and tools still lying in the workshops. Text 2: Odis Nyame observes that the same pattern turns up at sites documented as having emptied gradually: households leaving over several years take what they can carry and leave what they cannot, and heavy grain jars and anvils are exactly what they cannot.",
    "Based on the texts, Nyame's response to Bergen is best described as",
    ["showing that her evidence is equally consistent with a rival explanation.",
     "disputing the accuracy of the excavation on which she relies.",
     "agreeing with her conclusion while proposing a different date for it.",
     "arguing that the settlement was never permanently occupied at all."],
    "Cross-Text Connections",
    "Nyame accepts the finds and shows that gradual abandonment would leave the same traces, so the evidence cannot decide between the two. He challenges neither the excavation nor the fact of occupation."),

  R(6208, "craft", "H", 0,
    "Anyone reading the collected letters in order will notice that the correspondence thins to almost nothing between 1919 and 1922. The editors note the gap in a single line and move on. Whether the letters of those years were destroyed, were never written, or remain in a private collection is simply not known, and the editors are careful not to let the silence stand for any one of the three.",
    "Which choice best describes the function of the final sentence in the text?",
    ["It commends the editors for declining to interpret an absence of evidence.",
     "It criticizes the editors for failing to search private collections.",
     "It explains why the correspondence stopped during those three years.",
     "It summarizes what the letters of that period are known to contain."],
    "Text Structure and Purpose",
    "Listing three possibilities and noting that the editors refuse to choose among them approves their restraint. The text explicitly says the reason is not known, so it explains nothing and summarizes nothing."),

  // ── Information and Ideas ──────────────────────────────────────────────
  RP(6209, "info", "E", 0,
    "A tree's growth rings record more than its age. A wide ring marks a year of ample water and warmth; a narrow one marks drought or cold. Because trees in the same region respond to the same weather, their ring patterns match one another, and a sequence can be pushed back in time by overlapping timbers of different ages.",
    "Which choice best states the main idea of the text?",
    ["Growth rings record yearly conditions, and matching patterns allow sequences to be extended backwards.",
     "A wide growth ring always indicates that a tree is unusually old.",
     "Trees growing in different regions produce identical patterns of rings.",
     "The age of a tree can be determined only after the tree is felled."],
    "Central Ideas and Details",
    "The text explains what ring width records and then how matching patterns extend a chronology. Ring width tracks conditions rather than age, and the matching depends on trees sharing a region."),

  R(6210, "info", "M", 0,
    "Historian Sunna Lindqvist argues that the guild's apprenticeship rules functioned less to train newcomers to the craft than to limit how many craftsmen could enter the trade in any given decade.",
    "Which finding, if true, would most directly support Lindqvist's argument?",
    ["The required term of apprenticeship was lengthened in exactly those years when the number of working masters had risen.",
     "Apprentices were required to live in their master's household for the whole of the term.",
     "The guild's surviving records list the names of the apprentices admitted each year.",
     "Most apprentices completed the full term and were eventually admitted as masters."],
    "Command of Evidence",
    "Lindqvist's claim is about restricting entry, so the evidence must show the rules responding to the number of craftsmen rather than to training needs. Residence, record-keeping and completion rates say nothing about that."),

  R(6211, "info", "M", 0,
    "The species was known from a single valley and had never been recorded anywhere else, so its formal status was critically endangered. A recent survey using recorded calls rather than visual searches located it in eleven valleys across two provinces. The bird is small, drab, and almost entirely silent except at dawn. Researchers conclude that ______",
    "Which choice most logically completes the text?",
    ["the species was probably always more widespread than the earlier records suggested.",
     "the species has expanded its range very rapidly over the past few years.",
     "the earlier surveys must have been conducted in entirely the wrong season.",
     "the recorded calls drew birds from the original valley to the new sites."],
    "Inferences",
    "A small, drab, near-silent bird is easy to miss by sight, and switching to call-based survey found it in eleven valleys - so the earlier absence reflects detection, not distribution. A sudden range expansion or a mass attraction to playback would be far larger claims."),

  R(6212, "info", "H", 0,
    "A transport authority compared four bus corridors, recording for each the share of the route running on a dedicated lane and the average scheduled speed. The authority expected speed to rise as the share of dedicated lane rose, but suspected that the relationship would weaken once most of a route was already segregated from other traffic.",
    "Which choice best describes data from the table that support both parts of the authority's expectation?",
    ["Speed rose from 14.1 to 23.8 kilometres per hour as dedicated lane went from 22% to 74%, but only to 24.6 at 91%.",
     "Speed fell steadily as the share of dedicated lane increased across the four corridors.",
     "Speed was highest on the corridor with the smallest share of dedicated lane.",
     "Speed was identical on the South corridor and on the West corridor."],
    "Command of Evidence",
    "Both halves must be covered: speed climbs steeply to 74% dedicated lane, then gains only 0.8 more between 74% and 91%. The other choices reverse the trend or misread the last two rows, which differ.",
    "<table><thead><tr><th>Corridor</th><th>Dedicated lane (%)</th><th>Avg. speed (km/h)</th></tr></thead><tbody><tr><td>North</td><td>22</td><td>14.1</td></tr><tr><td>East</td><td>48</td><td>19.6</td></tr><tr><td>South</td><td>74</td><td>23.8</td></tr><tr><td>West</td><td>91</td><td>24.6</td></tr></tbody></table>"),

  R(6213, "info", "H", 0,
    "A publisher reissued a long out-of-print novel with a new cover and no other change. Sales in the first year exceeded the total of the previous twenty. Reviews of the reissue were few and largely unenthusiastic, and no adaptation or anniversary coincided with it. The book had, however, been named three months earlier in a widely shared list of neglected novels. An analyst concludes that ______",
    "Which choice most logically completes the text?",
    ["the recommendation, rather than the reissue itself, drove the increase in sales.",
     "the new cover was the principal reason that readers bought the book.",
     "the reviews of the reissue were more influential than they appeared to be.",
     "the novel's sales would have risen in that year no matter what happened."],
    "Inferences",
    "The text rules out reviews, adaptations and anniversaries, leaving the widely shared list as the one event preceding the surge. The cover changed too, but nothing connects it to the timing the way the list does."),

  R(6214, "info", "H", 0,
    "Every measurement of the expansion rate of the universe carries an uncertainty, and for decades those uncertainties were wide enough that all the estimates overlapped. As techniques improved the error bars narrowed - and two families of measurement, one based on nearby stars and one on the early universe, settled on values that no longer overlap at all. The disagreement did not appear because the measurements got worse. It appeared because they got better.",
    "Which choice best states the main idea of the text?",
    ["Improved precision exposed a real conflict that cruder measurements had concealed.",
     "The two families of measurement have converged on a single agreed value.",
     "Measurements of the expansion rate have become less reliable over time.",
     "Uncertainty in astronomical measurement can never be reduced past a fixed limit."],
    "Central Ideas and Details",
    "The last two sentences state it directly: better measurement, not worse, produced the disagreement. The values diverge rather than converge, and no fixed floor on uncertainty is claimed."),

  R(6215, "info", "H", 0,
    "Musicologist Farid Osei argues that the anonymous keyboard suite long attributed to a court composer was written for teaching rather than for performance at court.",
    "Which finding would most effectively support Osei's argument?",
    ["Each movement introduces exactly one new technical difficulty and then repeats it in progressively harder forms.",
     "The manuscript is bound in the same style as other volumes from the court library.",
     "The suite is written for an instrument that was common in wealthy households.",
     "The composer to whom the suite was attributed is known to have worked at the court."],
    "Command of Evidence",
    "A movement-by-movement progression through single difficulties is pedagogical design, which is exactly Osei's claim. The binding and the attribution point the other way, and the instrument's popularity is neutral."),

  // ── Standard English Conventions ───────────────────────────────────────
  R(6216, "conv", "E", 0,
    "The seed bank keeps its collection at minus twenty degrees, in sealed foil packets stacked on steel shelves. Power failures are the one serious risk to the whole arrangement ______",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    ["; a backup generator starts within seconds.",
     ", a backup generator starts within seconds.",
     " a backup generator starts within seconds.",
     ": a backup generator starts, within seconds."],
    "Boundaries",
    "Two independent clauses require a semicolon or a period. A comma alone is a splice, no punctuation is a run-on, and the last choice separates the verb from its modifier with a stray comma."),

  R(6217, "conv", "M", 0,
    "The review board declined to attribute the delay to any single department, and its language was carefully balanced throughout the report. It concluded that the schedule had slipped neither because of the design changes ______ because of the procurement freeze, but because the two had coincided.",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    ["nor", "or", "and", "also"],
    "Form, Structure, and Sense",
    "\"Neither\" pairs only with \"nor.\" The other options break the correlative construction."),

  R(6218, "conv", "M", 0,
    "The reading room occupies the whole of the upper floor and has not been altered in any significant way since 1908. Behind the librarian's desk ______ two oak cabinets holding the original catalogue cards.",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    ["stand", "stands", "has stood", "was standing"],
    "Form, Structure, and Sense",
    "The sentence is inverted: the subject is the plural \"two oak cabinets,\" which follows the verb. A plural subject takes \"stand.\""),

  R(6219, "conv", "H", 0,
    "Reviewers disagreed about almost every aspect of the new building, from its proportions to its choice of stone, and the debate ran for months in the architectural press. On one point, though, the criticism was unanimous ______",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    [": the entrance, hidden behind a service ramp.",
     "; the entrance, hidden behind a service ramp.",
     ", the entrance hidden behind a service ramp.",
     " the entrance; hidden behind a service ramp."],
    "Boundaries",
    "What follows the blank is a noun phrase, not an independent clause, so only a colon can introduce it. A semicolon needs a full clause on both sides."),

  R(6220, "conv", "H", 0,
    "The survey team spent three seasons recording every inscription on the site, including several that had been reported in the nineteenth century and never seen since. The resulting catalogue, comprising more than four thousand entries and cross-referenced to photographs taken from six angles, ______ the standard reference for the region.",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    ["has become", "have become", "are becoming", "become"],
    "Form, Structure, and Sense",
    "The subject is the singular \"catalogue\"; everything between the commas is a modifier. Only the singular \"has become\" agrees with it."),

  R(6221, "conv", "H", 0,
    "The instrument was designed to be carried up mountains by a single person, and every component was chosen with weight in mind. The mirror ______ remains the heaviest single part of the whole assembly.",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    [" - ground from a blank, polished by hand, and coated in the field - ",
     ", ground from a blank, polished by hand, and coated in the field - ",
     " - ground from a blank, polished by hand, and coated in the field, ",
     ", ground from a blank polished by hand and coated in the field "],
    "Boundaries",
    "The interrupting element contains commas of its own, so it must be set off with a matching pair of dashes. Mixing a comma with a dash leaves the boundary ambiguous."),

  R(6222, "conv", "H", 0,
    "The committee met four times before publishing anything at all, and its members were drawn from six different institutions in four countries. In the end the panel issued a single unsigned report, and ______ recommendations were adopted without amendment.",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    ["its", "it's", "their", "theirs"],
    "Form, Structure, and Sense",
    "The antecedent in this clause is \"the panel,\" a singular noun, so the singular possessive \"its\" is required. \"It's\" is a contraction and \"theirs\" cannot precede a noun."),

  // ── Expression of Ideas ────────────────────────────────────────────────
  R(6223, "expr", "M", 0,
    "Hydrogen burns without producing any carbon dioxide, which is why it is so often described as a clean fuel. Almost all of the hydrogen produced today, however, is made from natural gas by a process that releases carbon dioxide in quantity. ______, the fuel is clean at the point of use and considerably less so upstream.",
    "Which choice completes the text with the most logical transition?",
    ["In short", "By contrast", "Even so", "For example"],
    "Transitions",
    "The final sentence compresses the two preceding claims into one formulation, which calls for a summarizing transition. It is not a contrast with what precedes, a concession, or an example."),

  R(6224, "expr", "M", 0,
    "While researching a presentation, a student took the following notes: • The Rosetta Stone was found in 1799. • It carries the same decree written in three scripts. • Greek was already well understood by scholars at the time. • Comparing the Greek text with the hieroglyphs made decipherment possible.",
    "The student wants to explain why the stone proved so useful to scholars. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
    ["Because the stone repeats a single decree in three scripts, scholars could set the already familiar Greek against the hieroglyphs and begin to decipher them.",
     "The Rosetta Stone was discovered in 1799.",
     "The Rosetta Stone carries the same decree written in three different scripts.",
     "Greek was already well understood by scholars at the time of the discovery."],
    "Rhetorical Synthesis",
    "Usefulness comes from the combination: the same text in a known script and an unknown one. The other choices supply one ingredient each without the connection."),

  R(6225, "expr", "H", 0,
    "The standard account holds that the technique spread outward from a single workshop. Recent dating places the earliest examples in three separate regions within the same twenty-year window, too close together for any plausible route of transmission between them. ______, the technique appears to have been invented more than once.",
    "Which choice completes the text with the most logical transition?",
    ["Accordingly", "Nonetheless", "In particular", "Likewise"],
    "Transitions",
    "The final sentence draws the conclusion that the dating forces, so a consequence transition is needed. \"Nonetheless\" would set it against the evidence rather than following from it."),

  R(6226, "expr", "H", 0,
    "Restoring a painting always involves a judgement about how far to go. Removing every later addition can leave a work that no living person has ever seen, and that the artist may never have intended to survive unaltered. Leaving everything in place preserves centuries of other people's decisions alongside the original. ______, there is no neutral option, only a choice about which history to show.",
    "Which choice completes the text with the most logical transition?",
    ["Either way", "For instance", "By comparison", "Consequently"],
    "Transitions",
    "The final sentence covers both alternatives just laid out, which is what \"either way\" signals. \"Consequently\" would follow from only one of them, and the other two illustrate or compare."),

  R(6227, "expr", "H", 0,
    "While researching a presentation, a student took the following notes: • The Antonine Wall ran 63 kilometres across central Scotland. • It was built of turf on a stone foundation rather than of stone throughout. • It was held for roughly twenty years before being abandoned. • Hadrian's Wall, further south, was built of stone and served as the frontier for nearly three centuries.",
    "The student wants to contrast the two walls in a way that suggests why one lasted far longer as a frontier. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
    ["The Antonine Wall, built of turf on a stone foundation, was held for roughly twenty years, while the stone-built Hadrian's Wall to the south served as the frontier for nearly three centuries.",
     "The Antonine Wall ran for 63 kilometres across central Scotland.",
     "The Antonine Wall was built of turf laid on a stone foundation rather than of stone throughout.",
     "Hadrian's Wall was built of stone and remained in use for nearly three centuries."],
    "Rhetorical Synthesis",
    "The goal requires a contrast that pairs construction with duration for both walls. Each of the other choices describes only one wall or only one attribute."),
];
