/**
 * Digital SAT practice - Form A, Reading and Writing, MODULE 2 (LOWER route).
 *
 * Reached when module 1 went badly. Same blueprint and same 27 items, weighted
 * toward the easy end: E 15 / M 9 / H 3.
 *
 * ALL items and ALL passages are ORIGINAL, written from scratch for this app.
 * Domain blocks in the fixed order, easiest-to-hardest inside each block.
 * Do not sort this array, and never shuffle the choices. ids 5101-5199.
 */

import type { SatMcq } from "../types";
import { R, RP } from "./rwFactory";

export const FORM_A_RW_LOWER: SatMcq[] = [
  // ── Craft and Structure ────────────────────────────────────────────────
  R(5101, "craft", "E", 0,
    "The night market on Soi Sukhon has changed little in thirty years. The same families run the same stalls, the recipes are handed down unaltered, and even the metal stools are the ones the founders bought. Visitors who return after a decade away find the place reassuringly ______.",
    "Which choice completes the text with the most logical and precise word or phrase?",
    ["unchanged", "crowded", "expensive", "modern"],
    "Words in Context",
    "Everything listed - the families, the recipes, even the stools - has stayed the same, so returning visitors find the market unchanged. Nothing in the text concerns crowds, prices, or modernity."),

  R(5102, "craft", "E", 0,
    "Elephants can hear one another across several kilometres using calls pitched too low for human ears. The researchers who first recorded these rumbles were puzzled by what they had been watching for months: the animals seemed to coordinate their movements without any ______ signal that people could detect.",
    "Which choice completes the text with the most logical and precise word or phrase?",
    ["audible", "visible", "written", "chemical"],
    "Words in Context",
    "The puzzle is that the calls are too low for people to hear, so what was missing was an audible signal. The passage says nothing about visible, written, or chemical signalling."),

  RP(5103, "craft", "E", 0,
    "The first printed maps of the region were full of errors. Coastlines were guessed at, rivers were drawn hundreds of kilometres from their true courses, and whole islands appeared where there was only open sea. Later surveyors spent decades ______ these mistakes, one stretch of coast at a time.",
    "Which choice completes the text with the most logical and precise word or phrase?",
    ["correcting", "repeating", "ignoring", "inventing"],
    "Words in Context",
    "Surveyors working \"one stretch of coast at a time\" over decades were fixing the errors just described. Repeating, ignoring, or inventing them would not explain the effort."),

  R(5104, "craft", "E", 0,
    "Bamboo is often mistaken for a tree. It is in fact a grass, and that single distinction explains much of its behaviour: it grows from underground stems rather than from a trunk, it can add a metre of height in one day, and a harvested stand regrows without being replanted.",
    "Which choice best states the main purpose of the text?",
    ["To explain how classifying bamboo as a grass accounts for its unusual properties.",
     "To argue that bamboo should be planted in place of trees.",
     "To describe the process of harvesting bamboo commercially.",
     "To compare the height of bamboo with that of tropical trees."],
    "Text Structure and Purpose",
    "The text corrects the classification and then uses it to explain three behaviours. It makes no recommendation, gives no harvesting procedure, and draws no height comparison."),

  R(5105, "craft", "E", 0,
    "Most people picture a desert as an unbroken expanse of sand. By area, though, sand covers less than a fifth of the world's deserts. The rest is gravel plain, bare rock, cracked clay, and - in the coldest deserts of all - ice.",
    "Which choice best states the main purpose of the text?",
    ["To correct a common misconception about what deserts are made of.",
     "To explain how wind shapes sand into dunes.",
     "To argue that cold deserts are more common than hot ones.",
     "To describe the plants that manage to grow on gravel plains."],
    "Text Structure and Purpose",
    "The text names a popular image and then supplies figures that overturn it. Dune formation, the relative frequency of cold deserts, and desert plants are never discussed."),

  R(5106, "craft", "M", 0,
    "Before refrigeration reached the coast, fishing communities along the gulf preserved their catch with salt and sun. The particular methods varied from village to village, but all of them shared a single aim: to strip away the moisture in which spoilage organisms ______.",
    "Which choice completes the text with the most logical and precise word or phrase?",
    ["thrive", "dissolve", "freeze", "migrate"],
    "Words in Context",
    "Removing moisture works because spoilage organisms need it to flourish - they thrive in it. They do not dissolve, freeze, or migrate in moisture."),

  R(5107, "craft", "M", 0,
    "Text 1: Curator Petra Halden argues that museums should return objects taken during colonial rule, since the communities of origin have by far the strongest claim to them. Text 2: Historian Jomo Adeyemi supports return in principle but warns that many originating institutions still lack climate-controlled storage, and that objects sent back too quickly may be damaged beyond repair.",
    "Based on the texts, Adeyemi's position differs from Halden's mainly in that Adeyemi",
    ["raises a practical concern about how quickly returns should happen.",
     "denies that communities of origin have any claim to the objects.",
     "argues that museums should keep the disputed objects permanently.",
     "claims that colonial-era acquisitions were legitimate at the time."],
    "Cross-Text Connections",
    "Adeyemi accepts the principle and objects only to the pace, on conservation grounds. He never denies the claim, never argues for permanent retention, and never defends the original acquisitions."),

  R(5108, "craft", "H", 0,
    "The opening chapter of Nadia Roshan's memoir describes a single afternoon in her grandmother's kitchen in exhaustive detail: the pattern of the floor tiles, the weight of the stone pestle, the exact order in which the spices went into the pot. Only much later does the reader learn that the house was demolished the following spring, and that the chapter is the only record of it that now exists.",
    "Which choice best describes the function of the final sentence in the text?",
    ["It recasts the chapter's accumulated detail as an act of preservation.",
     "It suggests that the memoir's opening chapter is factually unreliable.",
     "It explains why the author eventually became interested in cooking.",
     "It introduces the central conflict of the memoir's later chapters."],
    "Text Structure and Purpose",
    "Learning that the house is gone and the chapter is its only record retroactively changes what the detail is for: it was preserving something. The sentence casts no doubt on accuracy, explains no career, and introduces no conflict."),

  // ── Information and Ideas ──────────────────────────────────────────────
  R(5109, "info", "E", 0,
    "Honeybees tell one another where food is by dancing. A returning forager traces a figure-eight pattern on the vertical comb. The angle of the straight run through the middle indicates the direction of the flowers relative to the sun, and the length of that run indicates how far away they are.",
    "Which choice best states the main idea of the text?",
    ["A honeybee's dance encodes both the direction of a food source and its distance.",
     "Honeybees prefer to gather from flowers that grow close to the hive.",
     "Bees dance mainly in order to attract mates within the colony.",
     "The figure-eight is the only movement bees ever make on the comb."],
    "Central Ideas and Details",
    "The last sentence assigns one meaning to the angle and another to the length, so the dance carries both direction and distance. Preference, mating, and exclusivity of the movement are never claimed."),

  RP(5110, "info", "E", 0,
    "In 2019 a coastal restoration team replanted mangroves along four kilometres of eroding shoreline. Five years later they measured both that stretch and an untouched stretch of comparable exposure nearby. The replanted shoreline had lost less than one metre of land; the untouched shoreline had lost more than eleven.",
    "According to the text, what did the team find?",
    ["The replanted shoreline eroded far less than the untouched shoreline.",
     "The two stretches of shoreline eroded at about the same rate.",
     "The untouched shoreline gained land over the five-year period.",
     "Mangroves grew more quickly along the untouched shoreline."],
    "Central Ideas and Details",
    "Less than one metre lost versus more than eleven is a large difference in favour of the replanted stretch. The other choices contradict those figures."),

  R(5111, "info", "E", 0,
    "Paper made from wood pulp yellows with age because it contains lignin, a compound that darkens when exposed to light and air. Paper made from cotton rag contains almost none. This is why a newspaper printed in the 1970s is already brittle and brown while a letter written in the 1770s can still be white.",
    "Which choice best states the main idea of the text?",
    ["Lignin content explains why some old paper yellows while other old paper does not.",
     "Newspapers today are printed on lower-quality paper than they once were.",
     "All paper made before 1800 was manufactured from cotton rag.",
     "Exposure to light is the only cause of paper deterioration over time."],
    "Central Ideas and Details",
    "The text contrasts two paper types and attributes the difference to lignin. It makes no claim about newspaper quality over time, no universal claim about pre-1800 paper, and no claim that light is the only factor."),

  R(5112, "info", "E", 0,
    "The lake's water level has fallen every year for two decades. Rainfall across the basin over the same period has not declined, and no new towns have been built on its shores. What has changed lies upstream: three irrigation canals now divert water from the river that feeds the lake. Researchers therefore conclude that ______",
    "Which choice most logically completes the text?",
    ["the upstream diversions are the likely cause of the decline.",
     "reduced rainfall accounts for most of the lake's decline.",
     "population growth around the lake caused the water loss.",
     "the lake's level will recover without any intervention."],
    "Inferences",
    "The text rules out rainfall and new settlement and names one thing that did change - the canals. That leaves the diversions as the remaining explanation. Nothing suggests spontaneous recovery."),

  R(5113, "info", "M", 0,
    "Farmers in the highlands have long planted maize and beans together in the same field rather than in separate plots. Agronomist Beatriz Solano proposed that this intercropping raises total yield per hectare, because the beans fix nitrogen in the soil that the maize can then take up.",
    "Which finding, if true, would most directly support Solano's proposal?",
    ["Plots planted with both crops produced 18% more total yield per hectare than plots of maize alone.",
     "Beans planted on their own matured two weeks earlier than beans planted alongside maize.",
     "Farmers in the highland region have grown maize for more than a thousand years.",
     "Maize requires substantially more water per hectare than beans do."],
    "Command of Evidence",
    "The proposal is about total yield per hectare, so the evidence must compare yields between intercropped and single-crop plots. Maturation timing, cultivation history, and water demand leave the yield claim untested."),

  R(5114, "info", "M", 0,
    "A city measured average summer surface temperatures in four neighbourhoods and recorded the share of each neighbourhood shaded by tree canopy. Planners expected that greater canopy cover would correspond to lower surface temperatures.",
    "Which choice best describes data from the table that support the planners' expectation?",
    ["Riverside, with 41% canopy cover, had the lowest average surface temperature, at 31.2 degrees Celsius.",
     "Depot, with the least canopy cover, had the lowest average surface temperature.",
     "Old Town and Market recorded the same average surface temperature.",
     "Canopy cover was greatest in the neighbourhood with the highest temperature."],
    "Command of Evidence",
    "The table pairs the highest canopy cover with the lowest temperature and the lowest cover with the highest temperature, exactly the expected relationship. Old Town and Market differ by 2.5 degrees.",
    "<table><thead><tr><th>Neighbourhood</th><th>Canopy cover (%)</th><th>Avg. surface temp (C)</th></tr></thead><tbody><tr><td>Riverside</td><td>41</td><td>31.2</td></tr><tr><td>Old Town</td><td>28</td><td>33.6</td></tr><tr><td>Market</td><td>15</td><td>36.1</td></tr><tr><td>Depot</td><td>6</td><td>38.4</td></tr></tbody></table>"),

  R(5115, "info", "H", 0,
    "A publisher's ledger from 1811 records the printing of 750 copies of a novel, of which 500 were bound at once and 250 left as unbound sheets. Booksellers' catalogues advertise the title continuously through the following decade, yet no surviving copy carries a binding dated later than 1813. Book historians infer that ______",
    "Which choice most logically completes the text?",
    ["the remaining sheets were bound and sold before 1814 rather than gradually over the decade.",
     "the novel was never actually printed in the quantity the ledger records.",
     "booksellers advertised the title without ever having any copies to sell.",
     "every copy bound after 1813 was later destroyed in a warehouse fire."],
    "Inferences",
    "Continuous advertising means copies were available throughout the decade, but no binding postdates 1813 - so the stock being sold must already have been bound by then. The other choices contradict the ledger, the catalogues, or introduce a fire the text never mentions."),

  // ── Standard English Conventions ───────────────────────────────────────
  R(5116, "conv", "E", 0,
    "The city's transport authority spent two years redesigning its bus network around a single principle: that no rider should ever wait longer than ten minutes. The new timetables, printed on a panel at every stop, ______ the frequency of each route in bold type.",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    ["list", "lists", "listing", "to list"],
    "Form, Structure, and Sense",
    "The subject is the plural \"timetables\"; the phrase between the commas is a modifier and cannot control the verb. The plural present \"list\" agrees."),

  R(5117, "conv", "E", 0,
    "Volcanic soil is unusually fertile, because minerals released as ash weathers are readily taken up by roots. Farmers on the slopes have long accepted the risk of living beside an active volcano ______",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    ["; the harvests are simply better there.",
     ", the harvests are simply better there.",
     " the harvests are simply better there.",
     ": the harvests are, simply better there."],
    "Boundaries",
    "Two independent clauses require a semicolon or a period. A comma alone is a comma splice, no punctuation is a run-on, and the final choice inserts a comma between subject and verb."),

  R(5118, "conv", "E", 0,
    "The letters were discovered in 2018, inside a trunk that had stood unopened in an attic since the war. By the time the archivist lifted the lid, the ink ______ so badly that several of the pages could not be read at all.",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    ["had faded", "has faded", "fades", "will fade"],
    "Form, Structure, and Sense",
    "The fading was complete before another past event - the archivist opening the trunk - so the past perfect is required. The other options are present perfect, simple present, and future."),

  R(5119, "conv", "E", 0,
    "Two research groups published competing accounts of the same eruption within a month of each other, drawing on the same seismic records but reading them differently. Each group insisted that ______ chronology was the accurate one.",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    ["its", "it's", "their", "they're"],
    "Form, Structure, and Sense",
    "\"Each group\" is singular, so the possessive pronoun is \"its.\" \"It's\" is the contraction of \"it is,\" \"their\" is plural, and \"they're\" is a contraction."),

  R(5120, "conv", "M", 0,
    "Few crops have travelled further from their place of origin than the chilli, and few have been absorbed so completely into the cuisines that adopted them. The chilli ______ native to the Americas, reached Asia only in the sixteenth century.",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    [", which is", ", which is,", " which is", "; which is"],
    "Boundaries",
    "The nonrestrictive clause needs a comma at each end, and the closing comma is already printed before \"reached.\" Doubling the comma, omitting it, or substituting a semicolon all break the pair."),

  R(5121, "conv", "M", 0,
    "The training programme for lighthouse keepers was famously demanding, and roughly a third of each intake withdrew before the end. Candidates spent six months learning to maintain the lamp, to read weather charts, and ______ small boats in heavy swell.",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    ["to handle", "handling", "handled", "handle"],
    "Form, Structure, and Sense",
    "The series is built from infinitives - to maintain, to read, and to handle. Only the infinitive keeps all three items parallel."),

  R(5122, "conv", "M", 0,
    "Coral spawning is timed with extraordinary precision across entire reef systems, and biologists still do not fully understand the cue. ______ colonies separated by many kilometres release their eggs within minutes of one another.",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    ["On certain nights after a full moon,",
     "On certain nights after a full moon",
     "On certain nights, after a full moon",
     "On certain nights after, a full moon"],
    "Boundaries",
    "An introductory prepositional phrase of this length takes a single comma at its end, before the subject \"colonies.\" The other placements either omit that comma or interrupt the phrase itself."),

  // ── Expression of Ideas ────────────────────────────────────────────────
  R(5123, "expr", "E", 0,
    "Aluminium is one of the most abundant metals in the earth's crust, more common than copper, zinc and tin combined. ______, it was once more valuable than gold, because nobody had found an economical way of separating it from its ore.",
    "Which choice completes the text with the most logical transition?",
    ["Nevertheless", "Consequently", "In addition", "For example"],
    "Transitions",
    "Abundance would normally mean cheapness, so the historical high price is a surprise - a contrast transition is needed. \"Consequently\" claims the opposite relationship, and the other two add or illustrate."),

  R(5124, "expr", "E", 0,
    "Tomatoes were grown in European gardens for roughly two centuries before anyone was willing to eat them, largely because their leaves resemble those of known poisonous plants. ______, they were cultivated only as ornamental curiosities.",
    "Which choice completes the text with the most logical transition?",
    ["For that reason", "In contrast", "However", "Similarly"],
    "Transitions",
    "The second sentence states the consequence of the fear described in the first, so a cause-and-effect transition fits. \"In contrast\" and \"however\" signal opposition; \"similarly\" signals likeness."),

  R(5125, "expr", "M", 0,
    "While researching a presentation, a student took the following notes: • The Bagan plain holds more than 2,000 surviving brick temples. • Most were built between the eleventh and thirteenth centuries. • An earthquake in 2016 damaged nearly 400 of them. • Restoration teams have used traditional brick-firing methods to match the originals.",
    "The student wants to explain how restorers have tried to preserve the temples' original character. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
    ["To repair the roughly 400 temples damaged by the 2016 earthquake, restoration teams have used traditional brick-firing methods that match the originals.",
     "The Bagan plain holds more than 2,000 surviving brick temples.",
     "Most of the temples on the Bagan plain were built between the eleventh and thirteenth centuries.",
     "An earthquake in 2016 damaged nearly 400 of the temples on the Bagan plain."],
    "Rhetorical Synthesis",
    "Only the first choice describes what restorers did and why it preserves the original character. The others give scale, date, or damage without addressing the restoration method."),

  R(5126, "expr", "M", 0,
    "Most bony fish control their buoyancy with a swim bladder, a gas-filled sac that can be inflated or emptied to hold the animal at a chosen depth. Sharks have no such organ. ______, they depend on an oily liver and on constant forward motion to keep from sinking.",
    "Which choice completes the text with the most logical transition?",
    ["Instead", "Therefore", "Likewise", "In fact"],
    "Transitions",
    "The third sentence names the substitute for the organ sharks lack, which calls for \"instead.\" \"Therefore\" would make it a consequence, \"likewise\" a parallel, and \"in fact\" an intensification."),

  R(5127, "expr", "H", 0,
    "While researching a presentation, a student took the following notes: • Traditional lacquerware requires up to thirty thin coats of sap. • Each coat must cure in a humid chamber for a full day. • A single bowl can take more than two months to finish. • Machine-made imitations can be produced in under an hour.",
    "The student wants to emphasize the labour involved in traditional lacquerware. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
    ["Because each of the up to thirty coats of sap must cure for a full day, a single traditional bowl can take more than two months to finish.",
     "Traditional lacquerware is made by applying thin coats of sap to a wooden form.",
     "Machine-made imitations of lacquerware can be produced in under an hour.",
     "Traditional lacquerware and machine-made imitations are made by different methods."],
    "Rhetorical Synthesis",
    "The labour is conveyed by joining the number of coats to the curing time and the resulting two months. The second and fourth choices are vague, and the third describes the imitation rather than the traditional process."),
];
