/**
 * Digital SAT practice - Form B, Reading and Writing, MODULE 1.
 *
 * ALL 27 items and ALL 27 passages are ORIGINAL, written from scratch for this
 * app. No College Board material, no excerpted or adapted published text.
 * Passages are 25-150 words, one per question.
 *
 * Domain blocks in the fixed order Craft and Structure -> Information and
 * Ideas -> Standard English Conventions -> Expression of Ideas,
 * easiest-to-hardest inside each block. Do not sort. ids 6001-6099.
 * Broad mix: E 9 / M 11 / H 7.
 */

import type { SatMcq } from "../types";
import { R, RP } from "./rwFactory";

export const FORM_B_RW_M1: SatMcq[] = [
  // ── Craft and Structure ────────────────────────────────────────────────
  R(6001, "craft", "E", 0,
    "For forty years the lighthouse at Cape Verin was kept by a single family, and the logbooks they left behind run to eleven volumes. Weather, shipping, repairs, the behaviour of the birds on the rocks - everything was written down. Historians now value the logs less for any single entry than for their sheer ______.",
    "Which choice completes the text with the most logical and precise word or phrase?",
    ["continuity", "brevity", "secrecy", "inaccuracy"],
    "Words in Context",
    "What makes the logs valuable is that one family recorded everything without a break for forty years - their continuity. Eleven volumes rules out brevity, and nothing suggests secrecy or error."),

  R(6002, "craft", "E", 0,
    "The street vendors in the old quarter cook in the open, a few steps from the people waiting to eat. Nothing about the process is hidden: the chopping, the frying and the assembly of each plate all happen in full view of the queue. That ______ is part of what regular customers say they trust.",
    "Which choice completes the text with the most logical and precise word or phrase?",
    ["transparency", "efficiency", "secrecy", "expense"],
    "Words in Context",
    "The passage stresses that nothing is hidden and everything happens in view, which is transparency. \"Secrecy\" is its opposite, and speed and cost are never mentioned."),

  R(6003, "craft", "E", 0,
    "Penguins are birds, a fact that seems less obvious the longer one watches them swim. Their wings have become flippers, dense and stiff rather than light and hollow, and their bones lack the air spaces that keep flying birds aloft. Every adaptation that makes a penguin a superb swimmer is one that makes flight impossible.",
    "Which choice best states the main purpose of the text?",
    ["To explain how the adaptations that suit penguins to swimming also rule out flight.",
     "To argue that penguins should not be classified as birds at all.",
     "To describe how penguins hunt for fish beneath the sea ice.",
     "To compare penguins with the other flightless birds of the world."],
    "Text Structure and Purpose",
    "The text lists swimming adaptations and closes by naming the trade-off explicitly. It affirms rather than denies that penguins are birds, and never covers hunting or other flightless species."),

  RP(6004, "craft", "M", 0,
    "The committee's first draft ran to ninety pages and pleased nobody. Members from every faction could find their own position stated somewhere in it, set out alongside the positions they had spent two years opposing. The document did not resolve the disagreement so much as ______ it.",
    "Which choice completes the text with the most logical and precise word or phrase?",
    ["catalogue", "conceal", "settle", "invent"],
    "Words in Context",
    "The draft lists every faction's position side by side without deciding between them - it catalogues the disagreement. \"Settle\" is what the sentence says it did not do, and the positions were neither hidden nor invented."),

  R(6005, "craft", "M", 0,
    "Granted, the earliest photographs required their subjects to sit still for several minutes, which is why so many nineteenth-century portraits look severe. But exposure times fell quickly. By the 1880s a photograph could be made in a fraction of a second, and the stiff pose survived less as a technical necessity than as a habit of the studio.",
    "Which choice best describes the function of the first sentence in the text as a whole?",
    ["It grants a point that the rest of the text goes on to limit.",
     "It states the conclusion that the rest of the text defends with evidence.",
     "It raises an objection that the rest of the text dismisses as false.",
     "It defines a technical term that the rest of the text goes on to use."],
    "Text Structure and Purpose",
    "\"Granted\" concedes the long exposures, and \"But\" in the next sentence restricts how far that explanation reaches. The concession is not called false - only insufficient for the later period."),

  R(6006, "craft", "M", 0,
    "Text 1: Linguist Marta Vey argues that a writing system's difficulty is best measured by how long children take to reach fluent reading, and that by this measure alphabets outperform character-based systems. Text 2: Kenji Aoto replies that time to fluency also tracks how much reading a society expects of young children, so comparisons across countries with very different schooling measure the schools at least as much as the scripts.",
    "Based on the texts, Aoto would most likely argue that Vey's measure",
    ["confounds features of the writing system with features of schooling.",
     "cannot be applied to character-based writing systems at all.",
     "shows that character-based systems are in fact easier than alphabets.",
     "should be replaced by a measure of adult literacy rates."],
    "Cross-Text Connections",
    "Aoto's objection is that two different things move the same number, so the measure cannot separate them. He does not say it is inapplicable, reverse Vey's conclusion, or propose adult literacy instead."),

  R(6007, "craft", "H", 0,
    "The treaty's drafters described the boundary only as \"the ridge dividing the two watersheds.\" At the time the phrase seemed sufficient, since the ridge was obvious to anyone standing on it. A century later, with the glacier gone and the drainage substantially altered, the wording has proved anything but ______.",
    "Which choice completes the text with the most logical and precise word or phrase?",
    ["determinate", "poetic", "recent", "brief"],
    "Words in Context",
    "The point is that the phrase no longer fixes a single line on the ground, so what it lacks is determinacy. It is certainly still brief, and neither poetry nor recency is at issue."),

  R(6008, "craft", "H", 0,
    "Hana Oyelaran's history of the postal service devotes its longest chapter to a subject the title never mentions: roads. Letters, she argues, moved no faster than the surfaces beneath them, and every improvement in delivery times across the period she covers traces back to paving, bridging or drainage rather than to anything the postal service itself did.",
    "Which choice best describes the function of the final sentence in the text?",
    ["It supplies the reasoning that makes an apparent digression central.",
     "It criticizes the author for straying from her announced subject.",
     "It summarizes the postal reforms that the book describes elsewhere.",
     "It identifies the period that the book covers in the most detail."],
    "Text Structure and Purpose",
    "The chapter on roads looks like a digression until the final sentence explains why roads determined postal speed - which makes the chapter central rather than stray. The sentence is an explanation, not a criticism or a summary."),

  // ── Information and Ideas ──────────────────────────────────────────────
  R(6009, "info", "E", 0,
    "Fungi do not photosynthesize. They feed instead by releasing enzymes into their surroundings and absorbing whatever those enzymes break down. This is why fungi turn up wherever dead material accumulates: in leaf litter, in rotting wood, in soil - anywhere there is something left to digest.",
    "Which choice best states the main idea of the text?",
    ["Fungi feed by digesting material outside their bodies, which explains where they are found.",
     "Fungi photosynthesize, but more slowly than green plants do.",
     "Most fungi live in soil rather than in wood or in leaf litter.",
     "Enzymes are produced by fungi and by no other kind of organism."],
    "Central Ideas and Details",
    "The text explains the feeding method and then links it directly to fungal habitat. It denies that fungi photosynthesize, treats all three habitats alike, and never claims enzymes are unique to fungi."),

  RP(6010, "info", "E", 0,
    "A research team measured how long each of 240 volunteers could hold a plank position: once after a full night's sleep, and once after being kept awake for twenty hours. Every volunteer completed both trials, in an order assigned at random. On average, the times recorded after the sleepless night were 22 percent shorter.",
    "According to the text, what did the team find?",
    ["Volunteers held the position for less time after being kept awake.",
     "Volunteers held the position for more time after being kept awake.",
     "Sleep had no measurable effect on how long volunteers could hold the position.",
     "Only some of the 240 volunteers completed both of the trials."],
    "Central Ideas and Details",
    "Times were 22 percent shorter after the sleepless night, and the text states that every volunteer completed both trials."),

  R(6011, "info", "M", 0,
    "The wreck lies in water far too deep for the diving technology of its period, and the ship's manifest lists no cargo valuable enough to justify a salvage attempt in any case. Yet the hold was found empty, and the timbers show cuts made by tools rather than by rock or ice. Marine archaeologists conclude that ______",
    "Which choice most logically completes the text?",
    ["the ship was stripped before it sank rather than afterwards.",
     "the manifest substantially understated the true value of the cargo.",
     "the wreck was salvaged with equipment unavailable at the time.",
     "the ship sank in shallower water and later drifted into the depths."],
    "Inferences",
    "Salvage after sinking is ruled out twice - by the depth and by the worthless cargo - yet tools clearly cut the timbers and the hold is empty. That points to the stripping happening before the ship went down."),

  R(6012, "info", "M", 0,
    "Historian Dele Amankwa argues that the town's rapid growth during the 1840s was driven by the new canal rather than by the textile mill that opened in the same decade, as earlier accounts had assumed.",
    "Which finding, if true, would most directly support Amankwa's argument?",
    ["Population rose fastest in the wards nearest the canal wharves and only slightly in the wards near the mill.",
     "The mill employed more workers in 1850 than any other single business in the town.",
     "The canal was completed two years before the textile mill opened.",
     "The town's population continued to grow steadily into the 1860s."],
    "Command of Evidence",
    "Amankwa's claim is about which of two simultaneous developments drove growth, so the evidence must separate them - and where the growth happened does exactly that. Mere precedence in time and later growth do not distinguish the two causes."),

  R(6013, "info", "M", 0,
    "A farming cooperative tested four rice varieties in the same field over a single season, recording both the yield of each variety and the amount of irrigation water it required. The cooperative was looking for a variety that produced a high yield without a high demand for water.",
    "Which choice best describes data from the table that identify the variety best meeting the cooperative's aim?",
    ["Sanpa produced 5.8 tonnes per hectare using 780 millimetres of water - nearly the highest yield for nearly the least water.",
     "Kholam produced the highest yield of the four varieties and also used the least water.",
     "Rewi produced the highest yield of any variety tested.",
     "Tako used less water than any of the other three varieties."],
    "Command of Evidence",
    "Sanpa's 5.8 tonnes is within 0.3 of the best yield while its 780 millimetres is within 20 of the lowest water use - the only variety strong on both measures. Kholam and Tako yield well but use far more water, and Rewi's yield is the lowest.",
    "<table><thead><tr><th>Variety</th><th>Yield (tonnes/ha)</th><th>Water used (mm)</th></tr></thead><tbody><tr><td>Kholam</td><td>6.1</td><td>1,180</td></tr><tr><td>Sanpa</td><td>5.8</td><td>780</td></tr><tr><td>Rewi</td><td>4.2</td><td>760</td></tr><tr><td>Tako</td><td>6.0</td><td>1,240</td></tr></tbody></table>"),

  R(6014, "info", "H", 0,
    "In the decade after the observatory was built, the number of comets reported from the surrounding region rose sharply. The observatory's own instruments, however, were configured for stellar photography and were poorly suited to comet searching, and none of the newly reported comets was first seen through them. What the observatory did bring was a monthly bulletin circulated to amateur astronomers across the district. Historians of science conclude that ______",
    "Which choice most logically completes the text?",
    ["the rise reflects better reporting by amateurs rather than better instruments.",
     "the observatory's instruments proved more capable than their designers had intended.",
     "comets genuinely became more frequent in that region during the decade.",
     "the amateur astronomers were being given access to the observatory's telescopes."],
    "Inferences",
    "The text rules out the observatory's instruments explicitly, leaving the bulletin - which reached amateurs - as the change that accompanied the rise. Nothing suggests more comets actually existed or that amateurs used the telescopes."),

  R(6015, "info", "H", 0,
    "Art historian Camille Sorge argues that the workshop's celebrated altarpiece was finished by assistants after the master's death, and not by the master himself as the surviving contract specifies.",
    "Which finding would most effectively support Sorge's argument?",
    ["Pigment analysis shows that the upper panels use a binder the workshop adopted only after the master died.",
     "The original contract for the altarpiece survives in the cathedral archive in good condition.",
     "The master is known to have employed at least six assistants over the course of his career.",
     "The altarpiece was installed in the cathedral three years after the contract was signed."],
    "Command of Evidence",
    "Only the binder evidence dates part of the painting to after the master's death, which is precisely Sorge's claim. The contract's survival, the existence of assistants, and the installation date are all compatible with the master having painted it himself."),

  // ── Standard English Conventions ───────────────────────────────────────
  R(6016, "conv", "E", 0,
    "The reef lies four kilometres offshore and can be reached only by boat, which has kept casual visitors away. Numbers have been capped by permit since 2019 ______",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    ["; the permits now sell out months in advance.",
     ", the permits now sell out months in advance.",
     " the permits now sell out months in advance.",
     ": the permits now sell out, months in advance."],
    "Boundaries",
    "Two independent clauses need a semicolon or a period. A comma alone is a splice, no punctuation is a run-on, and the last choice separates the subject from its verb."),

  R(6017, "conv", "E", 0,
    "The museum's board approved the loan in March, after nearly two years of negotiation with three separate institutions in two countries. The terms of the agreement ______ that the painted panel be returned within eighteen months.",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    ["require", "requires", "requiring", "to require"],
    "Form, Structure, and Sense",
    "The subject is the plural \"terms\"; \"of the agreement\" is a prepositional phrase and cannot control the verb. The plural \"require\" agrees."),

  R(6018, "conv", "E", 0,
    "The bridge was closed for structural repairs in January and did not reopen until September. By the time it reopened, the temporary ferry service that had replaced it ______ more than two hundred thousand passengers.",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    ["had carried", "has carried", "carries", "will carry"],
    "Form, Structure, and Sense",
    "The carrying was finished before another past event - the reopening - so the past perfect is required."),

  R(6019, "conv", "M", 0,
    "Only a handful of writers have won the prize twice within the same decade, and the rules were changed afterwards to make it harder. Amara Teoh ______ still the youngest winner in the prize's history, took it in 1998 and again in 2004.",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    [", who is", ", who is,", " who is", "; who is"],
    "Boundaries",
    "The nonrestrictive clause needs a comma at each end, and the closing comma is already printed before \"took.\" Doubling it, omitting it, or using a semicolon all break the pair."),

  R(6020, "conv", "M", 0,
    "The apprenticeship was designed to be broad rather than deep, on the theory that a builder should understand every trade on a site. Over three years each apprentice was expected to draft plans, to mix mortar, and ______ a wall without supervision.",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    ["to lay", "laying", "laid", "lays"],
    "Form, Structure, and Sense",
    "The series is built from infinitives - to draft, to mix, and to lay. Only the infinitive keeps the three items parallel."),

  R(6021, "conv", "M", 0,
    "The orchestra and the choir rehearsed separately for six weeks, in halls on opposite sides of the city, and met for the first time on the morning of the concert itself. Neither ensemble had heard ______ part performed alongside the other.",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    ["its", "it's", "their", "theirs"],
    "Form, Structure, and Sense",
    "\"Neither ensemble\" is singular, so the singular possessive \"its\" is correct. \"It's\" is a contraction, and \"theirs\" cannot come before a noun."),

  R(6022, "conv", "H", 0,
    "The itinerary had looked ambitious even before the flight delays began to accumulate during the second week. The tour visited Kyoto, Japan ______ Busan, South Korea; and Taipei, Taiwan.",
    "Which choice completes the text so that it conforms to the conventions of Standard English?",
    [";", ",", ":", " and"],
    "Boundaries",
    "When items in a series already contain commas, the items themselves are separated by semicolons. The semicolon already printed before \"and Taipei\" establishes the pattern."),

  // ── Expression of Ideas ────────────────────────────────────────────────
  R(6023, "expr", "E", 0,
    "Bicycles are among the most efficient machines ever built, converting a greater share of the rider's effort into forward motion than any other vehicle. ______, they remain difficult to use safely in cities that were designed entirely around the car.",
    "Which choice completes the text with the most logical transition?",
    ["Even so", "Therefore", "In addition", "For instance"],
    "Transitions",
    "The second sentence sets a drawback against the praise in the first, so a concessive contrast is needed. \"Therefore\" would make the difficulty a consequence of the efficiency."),

  R(6024, "expr", "M", 0,
    "The vaccine was developed in under a year, a pace without precedent. That speed came largely from work done long before the outbreak began: the delivery platform had been under development for a decade, and thousands of volunteers were already enrolled in trial registries. ______, the year was short only if the preceding decade is left out of the count.",
    "Which choice completes the text with the most logical transition?",
    ["In other words", "By contrast", "Nevertheless", "For example"],
    "Transitions",
    "The final sentence restates the preceding explanation in sharper form, which calls for a restatement transition. It neither contrasts, concedes, nor gives an instance."),

  R(6025, "expr", "M", 0,
    "While researching a presentation, a student took the following notes: • The Trans-Siberian Railway runs for about 9,300 kilometres. • Construction began in 1891 and the main line was completed in 1916. • The journey from Moscow to Vladivostok now takes about six days. • Before the railway was built, the same journey could take several months.",
    "The student wants to emphasize how much the railway shortened the journey. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
    ["A journey that could take several months before the railway was built now takes about six days.",
     "The Trans-Siberian Railway runs for about 9,300 kilometres.",
     "Construction of the railway began in 1891, and the main line was completed in 1916.",
     "The Trans-Siberian Railway connects Moscow with Vladivostok."],
    "Rhetorical Synthesis",
    "Only the first choice puts the two durations side by side, which is what \"how much it shortened\" requires. Length, construction dates, and endpoints do not make the comparison."),

  R(6026, "expr", "H", 0,
    "Machine translation has improved enormously, and for many routine documents it now produces text that needs no human revision at all. Literary translation is another matter entirely: rhythm, register and allusion still defeat it. ______, the systems fail least where the writing is most conventional, and most where it is most distinctive.",
    "Which choice completes the text with the most logical transition?",
    ["Put differently", "By contrast", "As a result", "Even so"],
    "Transitions",
    "The final sentence generalizes the two preceding observations into a single formulation - a restatement. It is not a contrast with what precedes, a consequence of it, or a concession."),

  R(6027, "expr", "H", 0,
    "While researching a presentation, a student took the following notes: • The Dutch Delta Works were begun after the North Sea flood of 1953. • That flood killed more than 1,800 people in the Netherlands. • The system includes dams, sluices and storm surge barriers. • The Maeslant barrier closes automatically when a dangerous surge is forecast.",
    "The student wants to explain what prompted the Delta Works and to give one example of how the system responds to danger. Which choice most effectively uses relevant information from the notes to accomplish both goals?",
    ["Begun after a 1953 North Sea flood that killed more than 1,800 people in the Netherlands, the Delta Works include the Maeslant barrier, which closes automatically whenever a dangerous surge is forecast.",
     "The Dutch Delta Works were begun after the North Sea flood of 1953.",
     "The Delta Works system includes dams, sluices and storm surge barriers.",
     "The Maeslant barrier closes automatically when a dangerous surge is forecast."],
    "Rhetorical Synthesis",
    "The goal has two parts, so the answer must supply both the prompting disaster and a specific automatic response. Each of the other choices covers only one half."),
];
