import type { Question } from "./questions";

/**
 * Original Physics question bank in SIIT/OSP entrance-exam style:
 * mechanics, electricity, waves & optics, thermal physics, and modern
 * physics. All items written from scratch. ids 4001+.
 * Use g = 9.8 m/s^2 unless a question states otherwise.
 */
const P = (
  id: number, topic: Question["topic"], kind: Question["kind"], answer: number,
  q: string, choices: string[], concept: string, explain: string,
): Question => ({
  id, topic, kind, timer: kind === "recall" ? 20 : 30, tag: "core", answer, q, choices,
  formula: concept, explain,
});

export const PHYSICS_QUESTIONS: Question[] = [
  // ── Mechanics (4001–4020) ──────────────────────────────────────
  P(4001,"mec","recall",1,"Newton's second law is best written as",
    ["$F=mv$","$F=ma$","$F=\\dfrac{m}{a}$","$F=\\dfrac{1}{2}mv^2$"],"Newton's second law","Force equals mass times acceleration."),
  P(4002,"mec","calc",2,"A $2\\,\\text{kg}$ object accelerates at $3\\,\\text{m/s}^2$. The net force is",
    ["$1.5\\,\\text{N}$","$5\\,\\text{N}$","$6\\,\\text{N}$","$0.67\\,\\text{N}$"],"F = ma","$F=2\\times 3=6\\,\\text{N}$."),
  P(4003,"mec","calc",0,"A car travels $150\\,\\text{m}$ in $10\\,\\text{s}$. Its average speed is",
    ["$15\\,\\text{m/s}$","$1500\\,\\text{m/s}$","$0.067\\,\\text{m/s}$","$25\\,\\text{m/s}$"],"Average speed","$v=d/t=150/10=15\\,\\text{m/s}$."),
  P(4004,"mec","calc",1,"An object dropped from rest falls for $2\\,\\text{s}$. Its speed is (use $g=9.8$)",
    ["$4.9\\,\\text{m/s}$","$19.6\\,\\text{m/s}$","$9.8\\,\\text{m/s}$","$39.2\\,\\text{m/s}$"],"v = gt","$v=gt=9.8\\times 2=19.6\\,\\text{m/s}$."),
  P(4005,"mec","recall",2,"The SI unit of work is the",
    ["newton","watt","joule","pascal"],"Units of work","Work is measured in joules (N·m)."),
  P(4006,"mec","calc",0,"A force of $10\\,\\text{N}$ moves a box $4\\,\\text{m}$ in its direction. The work done is",
    ["$40\\,\\text{J}$","$2.5\\,\\text{J}$","$14\\,\\text{J}$","$400\\,\\text{J}$"],"W = Fd","$W=10\\times 4=40\\,\\text{J}$."),
  P(4007,"mec","calc",3,"The kinetic energy of a $4\\,\\text{kg}$ object moving at $5\\,\\text{m/s}$ is",
    ["$20\\,\\text{J}$","$100\\,\\text{J}$","$40\\,\\text{J}$","$50\\,\\text{J}$"],"Kinetic energy","$KE=\\tfrac12 mv^2=\\tfrac12(4)(25)=50\\,\\text{J}$."),
  P(4008,"mec","calc",1,"The gravitational PE of a $2\\,\\text{kg}$ mass at height $5\\,\\text{m}$ (use $g=10$) is",
    ["$10\\,\\text{J}$","$100\\,\\text{J}$","$50\\,\\text{J}$","$25\\,\\text{J}$"],"Potential energy","$PE=mgh=2\\times 10\\times 5=100\\,\\text{J}$."),
  P(4009,"mec","recall",0,"Momentum is defined as",
    ["$p=mv$","$p=ma$","$p=\\tfrac12 mv^2$","$p=Ft^2$"],"Momentum","Momentum is mass times velocity."),
  P(4010,"mec","calc",2,"A $3\\,\\text{kg}$ trolley moves at $4\\,\\text{m/s}$. Its momentum is",
    ["$0.75\\,\\text{kg·m/s}$","$7\\,\\text{kg·m/s}$","$12\\,\\text{kg·m/s}$","$24\\,\\text{kg·m/s}$"],"p = mv","$p=3\\times 4=12\\,\\text{kg·m/s}$."),
  P(4011,"mec","recall",3,"On a frictionless surface, a moving object will",
    ["slow down","speed up","stop immediately","keep constant velocity"],"Newton's first law","With no net force, velocity stays constant (inertia)."),
  P(4012,"mec","calc",1,"The weight of a $10\\,\\text{kg}$ mass (use $g=9.8$) is",
    ["$10\\,\\text{N}$","$98\\,\\text{N}$","$9.8\\,\\text{N}$","$100\\,\\text{N}$"],"Weight","$W=mg=10\\times 9.8=98\\,\\text{N}$."),
  P(4013,"mec","calc",0,"A car accelerates from $10\\,\\text{m/s}$ to $30\\,\\text{m/s}$ in $4\\,\\text{s}$. Its acceleration is",
    ["$5\\,\\text{m/s}^2$","$10\\,\\text{m/s}^2$","$2.5\\,\\text{m/s}^2$","$20\\,\\text{m/s}^2$"],"a = Δv/t","$a=(30-10)/4=5\\,\\text{m/s}^2$."),
  P(4014,"mec","recall",2,"Which quantity is a vector?",
    ["speed","mass","velocity","temperature"],"Vectors vs scalars","Velocity has both magnitude and direction."),
  P(4015,"mec","calc",1,"Power delivered when $600\\,\\text{J}$ of work is done in $3\\,\\text{s}$ is",
    ["$1800\\,\\text{W}$","$200\\,\\text{W}$","$0.005\\,\\text{W}$","$603\\,\\text{W}$"],"Power","$P=W/t=600/3=200\\,\\text{W}$."),
  P(4016,"mec","recall",0,"For an object in uniform circular motion, the net force points",
    ["toward the centre","away from the centre","along the velocity","opposite the velocity"],"Centripetal force","Centripetal force is directed toward the centre."),
  P(4017,"mec","calc",3,"A ball is thrown straight up at $19.6\\,\\text{m/s}$ (use $g=9.8$). Time to reach the top is",
    ["$0.5\\,\\text{s}$","$1\\,\\text{s}$","$4\\,\\text{s}$","$2\\,\\text{s}$"],"Projectile motion","At the top $v=0$: $t=v/g=19.6/9.8=2\\,\\text{s}$."),
  P(4018,"mec","recall",1,"The coefficient of friction is a measure of",
    ["an object's mass","the resistance between surfaces","gravitational pull","air pressure"],"Friction","It quantifies how much two surfaces resist sliding."),
  P(4019,"mec","calc",2,"Using $v^2=u^2+2as$, a car braking from $20\\,\\text{m/s}$ to rest over $40\\,\\text{m}$ has acceleration",
    ["$-10\\,\\text{m/s}^2$","$-2\\,\\text{m/s}^2$","$-5\\,\\text{m/s}^2$","$-0.5\\,\\text{m/s}^2$"],"Kinematics","$0=400+2a(40)\\Rightarrow a=-5\\,\\text{m/s}^2$."),
  P(4020,"mec","recall",0,"Newton's third law states that forces come in",
    ["equal and opposite pairs","single pushes","random directions","pairs that add up"],"Newton's third law","Every action has an equal and opposite reaction."),

  // ── Electricity (4021–4035) ────────────────────────────────────
  P(4021,"ele","recall",1,"Ohm's law relates voltage, current, and resistance as",
    ["$V=I/R$","$V=IR$","$V=I+R$","$V=I^2R$"],"Ohm's law","Voltage equals current times resistance."),
  P(4022,"ele","calc",2,"A $12\\,\\text{V}$ supply drives $3\\,\\text{A}$ through a resistor. Its resistance is",
    ["$36\\,\\Omega$","$0.25\\,\\Omega$","$4\\,\\Omega$","$15\\,\\Omega$"],"R = V/I","$R=12/3=4\\,\\Omega$."),
  P(4023,"ele","calc",0,"The current through a $6\\,\\Omega$ resistor across $18\\,\\text{V}$ is",
    ["$3\\,\\text{A}$","$108\\,\\text{A}$","$24\\,\\text{A}$","$0.33\\,\\text{A}$"],"I = V/R","$I=18/6=3\\,\\text{A}$."),
  P(4024,"ele","recall",3,"The SI unit of electric charge is the",
    ["volt","ampere","ohm","coulomb"],"Units of charge","Charge is measured in coulombs."),
  P(4025,"ele","calc",1,"Two $4\\,\\Omega$ resistors in series give a total resistance of",
    ["$2\\,\\Omega$","$8\\,\\Omega$","$4\\,\\Omega$","$16\\,\\Omega$"],"Series resistance","Series resistances add: $4+4=8\\,\\Omega$."),
  P(4026,"ele","calc",0,"Two $4\\,\\Omega$ resistors in parallel give a total resistance of",
    ["$2\\,\\Omega$","$8\\,\\Omega$","$4\\,\\Omega$","$0.5\\,\\Omega$"],"Parallel resistance","$1/R=1/4+1/4=1/2\\Rightarrow R=2\\,\\Omega$."),
  P(4027,"ele","calc",2,"Electrical power in a device carrying $2\\,\\text{A}$ at $10\\,\\text{V}$ is",
    ["$5\\,\\text{W}$","$12\\,\\text{W}$","$20\\,\\text{W}$","$0.2\\,\\text{W}$"],"P = VI","$P=VI=10\\times 2=20\\,\\text{W}$."),
  P(4028,"ele","recall",1,"Charge $Q$, current $I$, and time $t$ are related by",
    ["$Q=I/t$","$Q=It$","$Q=I+t$","$Q=I/t^2$"],"Charge and current","Charge equals current times time."),
  P(4029,"ele","calc",3,"A current of $2\\,\\text{A}$ flows for $5\\,\\text{s}$. The charge transferred is",
    ["$0.4\\,\\text{C}$","$2.5\\,\\text{C}$","$7\\,\\text{C}$","$10\\,\\text{C}$"],"Q = It","$Q=2\\times 5=10\\,\\text{C}$."),
  P(4030,"ele","recall",0,"In a series circuit, the current is",
    ["the same everywhere","largest at the battery","zero in resistors","different in each part"],"Series current","Current is identical at every point in a series loop."),
  P(4031,"ele","recall",2,"A material that strongly resists current flow is called a(n)",
    ["conductor","semiconductor","insulator","superconductor"],"Conductors and insulators","Insulators strongly oppose the flow of charge."),
  P(4032,"ele","calc",1,"The power dissipated in a $5\\,\\Omega$ resistor carrying $2\\,\\text{A}$ is",
    ["$10\\,\\text{W}$","$20\\,\\text{W}$","$2.5\\,\\text{W}$","$50\\,\\text{W}$"],"P = I²R","$P=I^2R=4\\times 5=20\\,\\text{W}$."),
  P(4033,"ele","recall",0,"Like electric charges",
    ["repel each other","attract each other","have no force","always cancel"],"Coulomb's law","Like charges repel; unlike charges attract."),
  P(4034,"ele","calc",2,"Energy used by a $100\\,\\text{W}$ bulb in $60\\,\\text{s}$ is",
    ["$1.67\\,\\text{J}$","$160\\,\\text{J}$","$6000\\,\\text{J}$","$100\\,\\text{J}$"],"E = Pt","$E=Pt=100\\times 60=6000\\,\\text{J}$."),
  P(4035,"ele","recall",3,"In a parallel circuit, the voltage across each branch is",
    ["divided evenly by resistance","zero","larger than the source","the same as the source"],"Parallel voltage","Each parallel branch sees the full source voltage."),

  // ── Waves & Optics (4036–4048) ─────────────────────────────────
  P(4036,"wav","recall",1,"The wave equation relates speed, frequency, and wavelength as",
    ["$v=f/\\lambda$","$v=f\\lambda$","$v=\\lambda/f$","$v=f+\\lambda$"],"Wave equation","Wave speed equals frequency times wavelength."),
  P(4037,"wav","calc",2,"A wave has frequency $50\\,\\text{Hz}$ and wavelength $4\\,\\text{m}$. Its speed is",
    ["$12.5\\,\\text{m/s}$","$54\\,\\text{m/s}$","$200\\,\\text{m/s}$","$46\\,\\text{m/s}$"],"v = fλ","$v=50\\times 4=200\\,\\text{m/s}$."),
  P(4038,"wav","calc",0,"A wave travels at $340\\,\\text{m/s}$ with wavelength $2\\,\\text{m}$. Its frequency is",
    ["$170\\,\\text{Hz}$","$680\\,\\text{Hz}$","$342\\,\\text{Hz}$","$0.006\\,\\text{Hz}$"],"f = v/λ","$f=340/2=170\\,\\text{Hz}$."),
  P(4039,"wav","recall",3,"In a transverse wave, the particles oscillate",
    ["along the wave direction","in circles","not at all","perpendicular to the wave direction"],"Transverse waves","Particle motion is perpendicular to the direction of travel."),
  P(4040,"wav","recall",1,"Sound waves are",
    ["transverse","longitudinal","electromagnetic","stationary only"],"Longitudinal waves","Sound is a longitudinal (compression) wave."),
  P(4041,"wav","calc",2,"The period of a wave with frequency $25\\,\\text{Hz}$ is",
    ["$25\\,\\text{s}$","$0.25\\,\\text{s}$","$0.04\\,\\text{s}$","$4\\,\\text{s}$"],"T = 1/f","$T=1/25=0.04\\,\\text{s}$."),
  P(4042,"wav","recall",0,"When light passes from air into glass, it",
    ["bends toward the normal","bends away from the normal","does not bend","reflects entirely"],"Refraction","Entering a denser medium, light slows and bends toward the normal."),
  P(4043,"wav","recall",1,"The angle of incidence equals the angle of reflection is the law of",
    ["refraction","reflection","diffraction","dispersion"],"Law of reflection","Reflection keeps incidence and reflection angles equal."),
  P(4044,"wav","recall",2,"White light splitting into colours through a prism is called",
    ["reflection","refraction","dispersion","diffraction"],"Dispersion","Dispersion separates white light into its component colours."),
  P(4045,"wav","calc",3,"Red light of wavelength $700\\,\\text{nm}$ has a higher wavelength than blue light, so red has a",
    ["higher frequency","higher speed in vacuum","higher energy","lower frequency"],"Frequency and wavelength","Longer wavelength means lower frequency ($v=f\\lambda$)."),
  P(4046,"wav","recall",0,"The bending of waves around obstacles or through gaps is called",
    ["diffraction","reflection","refraction","polarization"],"Diffraction","Diffraction is the spreading of waves around edges or through gaps."),
  P(4047,"wav","recall",1,"A concave (converging) lens is thickest",
    ["at the edges","in the middle","uniformly","only at the top"],"Lenses","A converging (convex) lens is thickest in the middle; concave is thinnest there - the converging lens meant here is thickest in the middle."),
  P(4048,"wav","calc",2,"Light travels at $3\\times 10^8\\,\\text{m/s}$. Its frequency at wavelength $600\\,\\text{nm}$ is about",
    ["$1.8\\times 10^{2}\\,\\text{Hz}$","$5\\times 10^{5}\\,\\text{Hz}$","$5\\times 10^{14}\\,\\text{Hz}$","$2\\times 10^{-15}\\,\\text{Hz}$"],"f = c/λ","$f=(3\\times10^8)/(6\\times10^{-7})=5\\times10^{14}\\,\\text{Hz}$."),

  // ── Thermal Physics (4049–4056) ────────────────────────────────
  P(4049,"thm","recall",1,"Heat energy transfer through direct contact is called",
    ["convection","conduction","radiation","evaporation"],"Heat transfer","Conduction transfers heat through direct contact."),
  P(4050,"thm","recall",0,"Heat transfer by the movement of a fluid is called",
    ["convection","conduction","radiation","insulation"],"Heat transfer","Convection moves heat via circulating fluid."),
  P(4051,"thm","calc",2,"To raise $2\\,\\text{kg}$ of water ($c=4200\\,\\text{J/kg·K}$) by $10\\,\\text{K}$ requires",
    ["$8400\\,\\text{J}$","$21000\\,\\text{J}$","$84000\\,\\text{J}$","$420\\,\\text{J}$"],"Q = mcΔT","$Q=2\\times 4200\\times 10=84000\\,\\text{J}$."),
  P(4052,"thm","recall",3,"The Kelvin temperature $0\\,\\text{K}$ corresponds to",
    ["$0°\\text{C}$","$32°\\text{F}$","$100°\\text{C}$","absolute zero"],"Absolute zero","0 K is absolute zero, the lowest possible temperature."),
  P(4053,"thm","calc",1,"Convert $27°\\text{C}$ to kelvin.",
    ["$246\\,\\text{K}$","$300\\,\\text{K}$","$27\\,\\text{K}$","$327\\,\\text{K}$"],"Celsius to Kelvin","$K=°C+273=27+273=300\\,\\text{K}$."),
  P(4054,"thm","recall",0,"During a change of state (e.g. melting), the temperature",
    ["stays constant","always rises","always falls","doubles"],"Latent heat","Temperature is constant while latent heat drives the phase change."),
  P(4055,"thm","recall",2,"Which process transfers heat without any medium?",
    ["conduction","convection","radiation","diffusion"],"Radiation","Radiation transfers heat as electromagnetic waves, no medium needed."),
  P(4056,"thm","recall",1,"The first law of thermodynamics is a statement of",
    ["entropy increase","energy conservation","heat death","momentum conservation"],"First law","It expresses conservation of energy for heat and work."),

  // ── Modern Physics (4057–4065) ─────────────────────────────────
  P(4057,"mod","recall",1,"The energy of a photon is given by",
    ["$E=mc^2$","$E=hf$","$E=\\tfrac12 mv^2$","$E=IR$"],"Photon energy","Photon energy equals Planck's constant times frequency."),
  P(4058,"mod","recall",0,"Einstein's mass–energy relation is",
    ["$E=mc^2$","$E=hf$","$E=mgh$","$E=\\tfrac12 kx^2$"],"Mass–energy equivalence","$E=mc^2$ relates rest mass to energy."),
  P(4059,"mod","recall",2,"The particle emitted in the photoelectric effect is the",
    ["proton","neutron","electron","photon"],"Photoelectric effect","Incident photons eject electrons from a metal surface."),
  P(4060,"mod","recall",3,"An atom's nucleus contains",
    ["only protons","only electrons","electrons and protons","protons and neutrons"],"Atomic structure","The nucleus is made of protons and neutrons."),
  P(4061,"mod","recall",0,"Radioactive alpha particles are",
    ["helium nuclei","fast electrons","photons","free neutrons"],"Radioactivity","An alpha particle is a helium-4 nucleus (2p + 2n)."),
  P(4062,"mod","recall",1,"Beta-minus decay emits a",
    ["proton","high-speed electron","alpha particle","photon"],"Radioactivity","Beta-minus decay emits a fast electron from the nucleus."),
  P(4063,"mod","recall",2,"Gamma radiation is a form of",
    ["charged particle","sound wave","electromagnetic wave","nuclear fluid"],"Radioactivity","Gamma rays are high-energy electromagnetic radiation."),
  P(4064,"mod","calc",3,"After 2 half-lives, the fraction of a radioactive sample remaining is",
    ["$1$","$\\tfrac12$","$\\tfrac13$","$\\tfrac14$"],"Half-life","Each half-life halves the amount: $\\tfrac12\\times\\tfrac12=\\tfrac14$."),
  P(4065,"mod","recall",1,"Which has the greatest penetrating power?",
    ["alpha","gamma","beta","none penetrate"],"Radiation penetration","Gamma rays penetrate most; alpha is stopped by paper."),
];
